# -*- coding: utf-8 -*-
"""Anclaje de cada clase a una idea concreta de cada obra que cita.

`bibliografia.py` dice para qué sirve una obra. `aportes.py` cataloga las ideas
concretas que cada obra aporta. Este módulo cierra el circuito: para cada clase
declara **cuál** de esas ideas sostiene el contenido.

Formato: "PARTE.CLASE" -> {clave_de_obra: identificador_de_aporte}

Reglas que el validador exige:

1. Toda obra citada por la clase tiene anclaje. No se admite cita sin idea.
2. El identificador existe en `aportes.APORTES`.
3. El anclaje no puede coincidir con el «lente» general de la obra: si sirviera
   igual para cualquier clase, no es anclaje.

El anclaje no reemplaza la lectura: indica qué buscar y por qué.
"""

ANCLAJES = {
    # ---------------------------------------------------------------- Parte 01
    "01.01": {"drucker": "crear-cliente", "kotler": "mezcla", "diorio": "sistema-ingresos", "croll-yoskovitz": "una-metrica"},
    "01.02": {"kotler": "demanda", "christensen": "job", "ariely": "relatividad", "nagle": "valor-diferencial"},
    "01.03": {"levitt": "miopia", "porter": "cinco-fuerzas", "ries-trout": "escalera", "moore": "ciclo-adopcion"},
    "01.04": {"kotler": "valor-cliente", "miller-heiman": "roles-compra", "rackham": "avance", "moore": "producto-completo"},
    "01.05": {"kotler": "canales", "ellis-brown": "ciclo", "sharp": "disponibilidad", "croll-yoskovitz": "etapas"},
    "01.06": {"porter": "excedente", "nagle": "valor-diferencial", "simon": "palanca-precio", "ramanujam": "precio-primero"},
    "01.07": {"osterwalder-vpd": "encaje", "heath": "concrecion", "ries-trout": "mente", "fitzpatrick": "mom-test"},
    "01.08": {"kotler": "canales", "weinberg-traction": "bullseye", "chaffey": "medios-propios", "flint": "valor-canal"},
    "01.09": {"rumelt": "nucleo", "porter-hbr": "eficacia-vs-estrategia", "kotler": "mezcla", "doerr": "foco"},
    "01.10": {"rackham": "cierre-grande", "roberge": "proceso-comprador", "keenan": "diagnostico", "moore": "producto-completo"},
    "01.11": {"mehta": "resultado-cliente", "hulick": "primer-exito", "fader": "heterogeneidad", "dixon-effort": "esfuerzo"},
    "01.12": {"diorio": "modelo-datos", "roberge": "metricas-coaching", "grove": "indicadores-adelantados", "provost": "formulacion"},
    "01.13": {"cialdini": "escasez", "thaler": "sludge", "oneil": "armas", "godin": "permiso"},
    "01.14": {"diorio": "sistema-ingresos", "croll-yoskovitz": "modelos", "kaplan-norton": "mapa-estrategico", "kotler": "mezcla"},

    # ---------------------------------------------------------------- Parte 02
    "02.01": {"miller-heiman": "roles-compra", "dixon-customer": "mobilizer", "kotler": "valor-cliente", "solomon": "proceso-decision"},
    "02.02": {"ulwick": "resultados", "christensen": "job", "fitzpatrick": "mom-test", "osterwalder-vpd": "perfil"},
    "02.03": {"christensen": "dimensiones", "ulwick": "mapa-job", "fitzpatrick": "compromiso", "cagan": "riesgos"},
    "02.04": {"fitzpatrick": "preguntas-malas", "portigal": "sintesis", "solomon": "grupos-referencia", "kotler": "stp"},
    "02.05": {"moore": "beachhead", "ross": "tipos-lead", "fader": "heterogeneidad", "roberge": "proceso-comprador"},
    "02.06": {"dixon-customer": "consenso", "miller-heiman": "roles-compra", "rackham": "necesidad-explicita", "dixon-challenger": "adaptar"},
    "02.07": {"dixon-effort": "canal-preferido", "krug": "escaneo", "solomon": "proceso-decision", "kotler": "canales"},
    "02.08": {"krug": "no-pensar", "laja": "jerarquia-mensaje", "eisenberg": "friccion-formulario", "thaler": "arquitectura-decision"},
    "02.09": {"kahneman": "dos-sistemas", "thaler": "opcion-defecto", "ariely": "relatividad", "cialdini": "compromiso"},
    "02.10": {"cialdini": "autoridad", "rackham": "objeciones-prevencion", "dixon-effort": "esfuerzo", "godin": "permiso"},
    "02.11": {"rackham": "objeciones-prevencion", "keenan": "impacto", "blount": "rechazo", "cialdini": "compromiso"},
    "02.12": {"solomon": "cultura", "sharp2": "situaciones-compra", "cialdini": "prueba-social", "godin": "publico-minimo"},
    "02.13": {"fader": "rfm", "croll-yoskovitz": "cohortes", "kaushik": "segmentacion", "flint": "recompra"},
    "02.14": {"fitzpatrick": "compromiso", "osterwalder-vpd": "prueba", "christensen": "circunstancia", "roberge": "proceso-comprador"},

    # ---------------------------------------------------------------- Parte 03
    "03.01": {"hubbard": "valor-informacion", "malhotra": "diseno-investigacion", "fitzpatrick": "mom-test", "provost": "formulacion"},
    "03.02": {"malhotra": "error-total", "hubbard": "medicion-definicion", "provost": "evaluacion", "porter": "senales"},
    "03.03": {"fitzpatrick": "preguntas-malas", "portigal": "conducir", "blank": "fuera-del-edificio", "malhotra": "cuestionario"},
    "03.04": {"malhotra": "cuestionario", "hubbard": "calibracion", "provost": "evaluacion", "kaushik": "plan-medicion"},
    "03.05": {"malhotra": "muestreo", "provost": "asociacion-causalidad", "hubbard": "dilema-medicion", "kohavi": "confianza"},
    "03.06": {"portigal": "sintesis", "fitzpatrick": "elogios", "malhotra": "diseno-investigacion", "christensen": "circunstancia"},
    "03.07": {"provost": "asociacion-causalidad", "kohavi": "efecto-minimo", "malhotra": "escalas", "wheeler-dv": "variacion-comun"},
    "03.08": {"moore": "beachhead", "hubbard": "calibracion", "malhotra": "muestreo", "osterwalder-bmg": "nueve-bloques"},
    "03.09": {"porter": "grupos-estrategicos", "porter-hbr": "eficacia-vs-estrategia", "kim-mauborgne": "curva-valor", "ries-trout": "escalera"},
    "03.10": {"porter": "competidor", "rumelt": "diagnostico", "kim-mauborgne": "no-clientes", "porter-hbr": "renuncia"},
    "03.11": {"kaushik": "multiplicidad", "godin": "publico-minimo", "chaffey": "medios-propios", "solomon": "cultura"},
    "03.12": {"ellet": "evidencia-caso", "provost": "formulacion", "rumelt": "diagnostico", "hubbard": "valor-informacion"},
    "03.13": {"ries-lean": "aprendizaje-validado", "kohavi": "confianza", "blank": "hipotesis", "hubbard": "medicion-definicion"},
    "03.14": {"ellet": "argumento", "malhotra": "error-total", "hubbard": "calibracion", "rumelt": "nucleo"},

    # ---------------------------------------------------------------- Parte 04
    "04.01": {"kotler": "stp", "sharp": "compradores-ligeros", "fader": "heterogeneidad", "rumelt": "mala-estrategia"},
    "04.02": {"sharp": "penetracion", "solomon": "identidad", "kotler": "stp", "fader": "rfm"},
    "04.03": {"moore": "beachhead", "ross": "especializacion", "fader": "centricidad", "roberge": "contratacion-datos"},
    "04.04": {"provost": "sobreajuste", "fader": "rfm", "croll-yoskovitz": "cohortes", "kaushik": "segmentacion"},
    "04.05": {"kotler": "stp", "moore": "producto-completo", "porter": "cinco-fuerzas", "rumelt": "foco"},
    "04.06": {"rumelt": "foco", "porter-hbr": "renuncia", "moore": "beachhead", "doerr": "foco"},
    "04.07": {"moore": "beachhead", "godin": "publico-minimo", "porter": "grupos-estrategicos", "kim-mauborgne": "no-clientes"},
    "04.08": {"porter-hbr": "encaje", "ries-trout": "primero", "sharp2": "activos-distintivos", "aaker": "equity"},
    "04.09": {"keller-brand": "paridad-diferencia", "kotler": "stp", "ries-trout": "escalera", "sharp": "diferenciacion"},
    "04.10": {"ries-trout": "mente", "keller-brand": "medicion", "malhotra": "escalas", "aaker": "posicion"},
    "04.11": {"ries-trout": "mente", "keller-brand": "cbbe", "kotler": "stp", "aaker": "identidad"},
    "04.12": {"ries-trout": "reposicionar", "aaker": "arquitectura", "keller-brand": "resonancia", "rumelt": "diagnostico"},
    "04.13": {"heath": "maldicion-conocimiento", "keller-brand": "medicion", "kohavi": "confianza", "malhotra": "escalas"},
    "04.14": {"kotler": "stp", "rumelt": "nucleo", "ries-trout": "nombre", "moore": "referencias"},

    # ---------------------------------------------------------------- Parte 05
    "05.01": {"kotler": "mezcla", "cagan": "resultado-output", "osterwalder-vpd": "mapa-valor", "mehta": "resultado-cliente"},
    "05.02": {"osterwalder-vpd": "perfil", "christensen": "job", "fitzpatrick": "mom-test", "cagan": "riesgos"},
    "05.03": {"ries-lean": "mvp", "fitzpatrick": "compromiso", "blank": "customer-discovery", "cagan": "descubrimiento"},
    "05.04": {"ries-lean": "mvp", "cagan": "riesgos", "blank": "hipotesis", "kohavi": "confianza"},
    "05.05": {"ellis-brown": "must-have", "croll-yoskovitz": "etapas", "cagan": "descubrimiento", "ries-lean": "contabilidad-innovacion"},
    "05.06": {"ramanujam": "empaquetado", "nagle": "valor-diferencial", "sugarman": "coherencia-promesa", "cialdini": "escasez"},
    "05.07": {"ramanujam": "empaquetado", "nagle": "segmentacion-precio", "smith-pricing": "versionado", "ariely": "relatividad"},
    "05.08": {"nagle": "sensibilidad", "cialdini": "reciprocidad", "dixon-effort": "resolucion-siguiente", "ramanujam": "modelo-monetizacion"},
    "05.09": {"kotler": "ciclo-vida", "moore": "ciclo-adopcion", "porter": "grupos-estrategicos", "cagan": "roadmap"},
    "05.10": {"kotler": "mezcla", "cagan": "roadmap", "rumelt": "foco", "aaker": "arquitectura"},
    "05.11": {"cagan": "roadmap", "ries-lean": "aprendizaje-validado", "roberge": "proceso-comprador", "doerr": "okr"},
    "05.12": {"dixon-effort": "lenguaje", "mehta": "salud", "reichheld": "cierre-circuito", "portigal": "sintesis"},
    "05.13": {"ramanujam": "disposicion-pagar", "blank": "customer-discovery", "ries-lean": "construir-medir", "fitzpatrick": "compromiso"},
    "05.14": {"ramanujam": "modelo-monetizacion", "roberge": "formacion", "weinberg-sales": "relato-comercial", "osterwalder-vpd": "encaje"},

    # ---------------------------------------------------------------- Parte 06
    "06.01": {"sharp": "disponibilidad", "sharp2": "estructuras-memoria", "keller-brand": "cbbe", "aaker": "equity"},
    "06.02": {"aaker": "identidad", "keller-brand": "medicion", "wheeler": "proceso", "sharp2": "activos-distintivos"},
    "06.03": {"sinek": "porque", "godin": "cambio", "aaker": "identidad", "collins": "erizo"},
    "06.04": {"wheeler": "aplicabilidad", "ries-trout": "nombre", "keller-brand": "cbbe", "heath": "succes"},
    "06.05": {"handley": "estandar-editorial", "heath": "concrecion", "wheeler": "gobierno", "sugarman": "coherencia-promesa"},
    "06.06": {"sharp2": "activos-distintivos", "wheeler": "aplicabilidad", "aaker": "posicion", "krug": "jerarquia-visual"},
    "06.07": {"aaker": "arquitectura", "keller-brand": "cbbe", "sharp2": "consistencia", "kotler": "mezcla"},
    "06.08": {"heath": "succes", "godin": "cambio", "sugarman": "resbaladilla", "handley": "empatia"},
    "06.09": {"keller-brand": "cbbe", "aaker": "equity", "binet-field": "corto-largo", "sharp": "disponibilidad"},
    "06.10": {"reichheld": "proposito", "godin": "permiso", "dixon-effort": "resolucion-siguiente", "cialdini": "autoridad"},
    "06.11": {"godin": "publico-minimo", "handley": "utilidad", "collins": "personas-primero", "lencioni": "confianza"},
    "06.12": {"chaffey": "omnicanal", "flint": "migracion-clientes", "krug": "no-pensar", "kotler": "canales"},
    "06.13": {"binet-field": "metricas-sesgo", "keller-brand": "medicion", "sharp": "penetracion", "kaushik": "plan-medicion"},
    "06.14": {"wheeler": "gobierno", "aaker": "identidad", "handley": "estandar-editorial", "sharp2": "consistencia"},

    # ---------------------------------------------------------------- Parte 07
    "07.01": {"simon": "palanca-precio", "nagle": "politica", "ramanujam": "precio-primero", "smith-pricing": "estructura"},
    "07.02": {"nagle": "costo-piso", "simon": "valor-percibido", "smith-pricing": "estructura", "croll-yoskovitz": "modelos"},
    "07.03": {"nagle": "valor-diferencial", "porter": "cinco-fuerzas", "simon": "guerra-precios", "smith-pricing": "price-fences"},
    "07.04": {"nagle": "valor-diferencial", "ramanujam": "disposicion-pagar", "simon": "valor-percibido", "hubbard": "medicion-definicion"},
    "07.05": {"ramanujam": "disposicion-pagar", "nagle": "sensibilidad", "hubbard": "calibracion", "malhotra": "cuestionario"},
    "07.06": {"nagle": "sensibilidad", "kohavi": "efecto-minimo", "simon": "psicologia-precio", "smith-pricing": "price-fences"},
    "07.07": {"malhotra": "escalas", "nagle": "sensibilidad", "ramanujam": "disposicion-pagar", "hubbard": "dilema-medicion"},
    "07.08": {"smith-pricing": "price-fences", "nagle": "segmentacion-precio", "ramanujam": "empaquetado", "simon": "valor-percibido"},
    "07.09": {"croll-yoskovitz": "modelos", "mehta": "expansion", "ramanujam": "modelo-monetizacion", "fader-ltv": "ltv-modelo"},
    "07.10": {"bush-plg": "modelo-gratuito", "croll-yoskovitz": "una-metrica", "ramanujam": "modelo-monetizacion", "ellis-brown": "aha"},
    "07.11": {"nagle": "cascada", "simon": "guerra-precios", "fisher-ury": "criterios-objetivos", "zoltners": "incentivos"},
    "07.12": {"croll-yoskovitz": "modelos", "fader-ltv": "ltv-modelo", "provost": "valor-esperado", "hubbard": "calibracion"},
    "07.13": {"kohavi": "guardarrailes", "nagle": "politica", "provost": "evaluacion", "simon": "psicologia-precio"},
    "07.14": {"nagle": "politica", "ramanujam": "modelo-monetizacion", "simon": "palanca-precio", "croll-yoskovitz": "modelos"},

    # ---------------------------------------------------------------- Parte 08
    "08.01": {"roberge": "proceso-comprador", "weinberg-sales": "proceso-nueva-venta", "rackham": "avance", "grove": "output-gerencial"},
    "08.02": {"blount": "disciplina", "weinberg-sales": "lista-objetivo", "ross": "cold-calling-2", "bertuzzi": "especializacion-sdr"},
    "08.03": {"rackham": "avance", "voss": "espejo", "keenan": "estado-actual", "cialdini": "reciprocidad"},
    "08.04": {"rackham": "implicacion", "keenan": "diagnostico", "dixon-challenger": "ensenar", "fitzpatrick": "mom-test"},
    "08.05": {"miller-heiman": "senal-alerta", "roberge": "metricas-coaching", "keenan": "impacto", "ross": "tipos-lead"},
    "08.06": {"rackham": "necesidad-explicita", "keenan": "brecha", "dixon-challenger": "insight-comercial", "krug": "no-pensar"},
    "08.07": {"ellet": "argumento", "heath": "succes", "handley": "utilidad", "dixon-customer": "habilitar"},
    "08.08": {"nagle": "politica", "fisher-ury": "criterios-objetivos", "ellet": "analisis-decision", "handley": "edicion"},
    "08.09": {"rackham": "objeciones-prevencion", "voss": "etiquetado", "keenan": "impacto", "cialdini": "compromiso"},
    "08.10": {"blount": "cadencia", "weinberg-sales": "relato-comercial", "roberge": "metricas-coaching", "ross": "pipeline-predecible"},
    "08.11": {"rackham": "cierre-grande", "fisher-ury": "opciones", "keenan": "brecha", "cialdini": "escasez"},
    "08.12": {"mehta": "resultado-cliente", "roberge": "proceso-comprador", "hulick": "primer-exito", "diorio": "friccion"},
    "08.13": {"roberge": "metricas-coaching", "diorio": "modelo-datos", "grove": "indicadores-adelantados", "provost": "formulacion"},
    "08.14": {"roberge": "formacion", "weinberg-sales": "proceso-nueva-venta", "rackham": "spin", "bertuzzi": "modelo-sdr"},

    # ---------------------------------------------------------------- Parte 09
    "09.01": {"rackham": "implicacion", "keenan": "diagnostico", "dixon-challenger": "ensenar", "miller-heiman": "resultado-ganar"},
    "09.02": {"rackham": "spin", "keenan": "impacto", "fitzpatrick": "preguntas-malas", "dixon-challenger": "adaptar"},
    "09.03": {"dixon-challenger": "perfiles", "dixon-customer": "mobilizer", "rackham": "implicacion", "keenan": "brecha"},
    "09.04": {"keenan": "brecha", "rackham": "necesidad-explicita", "dixon-challenger": "insight-comercial", "cagan": "riesgos"},
    "09.05": {"miller-heiman": "roles-compra", "roberge": "proceso-comprador", "dixon-customer": "consenso", "rackham": "avance"},
    "09.06": {"rackham": "necesidad-explicita", "keenan": "diagnostico", "ross": "tipos-lead", "roberge": "metricas-coaching"},
    "09.07": {"dixon-customer": "consenso", "miller-heiman": "roles-compra", "rackham": "avance", "shell": "autoridad"},
    "09.08": {"miller-heiman": "resultado-ganar", "dixon-customer": "habilitar", "rackham": "avance", "shell": "autoridad"},
    "09.09": {"miller-heiman": "plan-cuenta", "dixon-customer": "disrupcion-interna", "porter": "competidor", "shell": "legitimidad"},
    "09.10": {"miller-heiman": "plan-cuenta", "ross": "especializacion", "dixon-customer": "habilitar", "bertuzzi": "modelo-sdr"},
    "09.11": {"miller-heiman": "senal-alerta", "shell": "legitimidad", "porter": "senales", "malhotra-neg": "preparacion"},
    "09.12": {"fisher-ury": "intereses", "malhotra-neg": "tacticas-dificiles", "nagle": "cascada", "shell": "autoridad"},
    "09.13": {"miller-heiman": "plan-cuenta", "dixon-customer": "consenso", "mehta": "segmentacion-cs", "zoltners": "territorios"},
    "09.14": {"miller-heiman": "senal-alerta", "roberge": "metricas-coaching", "grove": "reuniones", "ellet": "analisis-decision"},

    # ---------------------------------------------------------------- Parte 10
    "10.01": {"malhotra-neg": "preparacion", "fisher-ury": "intereses", "shell": "estilos", "voss": "preguntas-calibradas"},
    "10.02": {"fisher-ury": "intereses", "malhotra-neg": "crear-reclamar", "ury": "reencuadre", "shell": "legitimidad"},
    "10.03": {"fisher-ury": "batna", "malhotra-neg": "zopa", "shell": "autoridad", "ury": "poder-educar"},
    "10.04": {"malhotra-neg": "zopa", "fisher-ury": "opciones", "shell": "legitimidad", "nagle": "valor-diferencial"},
    "10.05": {"malhotra-neg": "preparacion", "kahneman": "anclaje", "voss": "preguntas-calibradas", "ariely": "precio-ancla"},
    "10.06": {"malhotra-neg": "crear-reclamar", "fisher-ury": "opciones", "shell": "estilos", "nagle": "cascada"},
    "10.07": {"nagle": "cascada", "malhotra-neg": "zopa", "fisher-ury": "criterios-objetivos", "simon": "guerra-precios"},
    "10.08": {"fisher-ury": "opciones", "nagle": "segmentacion-precio", "malhotra-neg": "crear-reclamar", "grove": "delegacion"},
    "10.09": {"fisher-ury": "criterios-objetivos", "malhotra-neg": "etica", "nagle": "politica", "iso-31000": "riesgo-residual"},
    "10.10": {"malhotra-neg": "tacticas-dificiles", "fisher-ury": "intereses", "shell": "autoridad", "nagle": "valor-diferencial"},
    "10.11": {"ury": "no-reaccionar", "voss": "etiquetado", "malhotra-neg": "tacticas-dificiles", "shell": "estilos"},
    "10.12": {"shell": "cultura", "fisher-ury": "personas-problema", "malhotra-neg": "informacion", "solomon": "cultura"},
    "10.13": {"fisher-ury": "criterios-objetivos", "malhotra-neg": "etica", "grove": "reuniones", "ellet": "argumento"},
    "10.14": {"malhotra-neg": "crear-reclamar", "fisher-ury": "batna", "ury": "puente-dorado", "shell": "legitimidad"},

    # ---------------------------------------------------------------- Parte 11
    "11.01": {"binet-field": "60-40", "godin": "permiso", "weinberg-traction": "canales", "chaffey": "medios-propios"},
    "11.02": {"blount": "cadencia", "godin": "permiso", "handley": "empatia", "oneil": "proxy"},
    "11.03": {"blount": "bloques", "bertuzzi": "metricas-sdr", "weinberg-sales": "lista-objetivo", "ross": "tipos-lead"},
    "11.04": {"blount": "cadencia", "handley": "utilidad", "bertuzzi": "especializacion-sdr", "sugarman": "coherencia-promesa"},
    "11.05": {"blount": "rechazo", "weinberg-sales": "relato-comercial", "bertuzzi": "especializacion-sdr", "ross": "cold-calling-2"},
    "11.06": {"blount": "disciplina", "godin": "permiso", "handley": "empatia", "vaynerchuk": "aporte-antes"},
    "11.07": {"cialdini": "reciprocidad", "godin": "cambio", "blount": "bloques", "collins": "personas-primero"},
    "11.08": {"reichheld": "cliente-ganado", "cialdini": "reciprocidad", "mehta": "expansion", "godin": "permiso"},
    "11.09": {"godin": "publico-minimo", "weinberg-traction": "bullseye", "chaffey": "modelo-canal", "blount": "bloques"},
    "11.10": {"godin": "permiso", "handley": "utilidad", "pulizzi": "nicho-contenido", "chaffey": "medios-propios"},
    "11.11": {"roberge": "demanda", "ross": "especializacion", "chaffey": "planificacion", "diorio": "friccion"},
    "11.12": {"roberge": "demanda", "diorio": "definiciones", "provost": "evaluacion", "ross": "pipeline-predecible"},
    "11.13": {"blount": "cadencia", "bertuzzi": "metricas-sdr", "ross": "pipeline-predecible", "handley": "edicion"},
    "11.14": {"ross": "pipeline-predecible", "bertuzzi": "modelo-sdr", "blount": "disciplina", "roberge": "formacion"},

    # ---------------------------------------------------------------- Parte 12
    "12.01": {"chaffey": "planificacion", "binet-field": "60-40", "kaushik": "plan-medicion", "weinberg-traction": "bullseye"},
    "12.02": {"krug": "no-pensar", "eisenberg": "escenarios", "laja": "jerarquia-mensaje", "chaffey": "medios-propios"},
    "12.03": {"laja": "jerarquia-mensaje", "eisenberg": "hipotesis-cro", "krug": "escaneo", "kohavi": "confianza"},
    "12.04": {"enge-seo": "intencion", "chaffey": "medios-propios", "pulizzi": "nicho-contenido", "kaushik": "segmentacion"},
    "12.05": {"geddes": "estructura-cuenta", "kaushik": "so-what", "chaffey": "modelo-canal", "eisenberg": "escenarios"},
    "12.06": {"handley": "utilidad", "chaffey": "medios-propios", "kaushik": "segmentacion", "godin": "permiso"},
    "12.07": {"godin": "cambio", "vaynerchuk": "contexto-canal", "chaffey": "modelo-canal", "handley": "empatia"},
    "12.08": {"godin": "publico-minimo", "pulizzi": "audiencia-primero", "reichheld": "proposito", "handley": "empatia"},
    "12.09": {"laja": "investigacion-previa", "kohavi": "detencion-temprana", "eisenberg": "hipotesis-cro", "krug": "prueba-usabilidad"},
    "12.10": {"kaushik": "vanidad", "provost": "formulacion", "croll-yoskovitz": "una-metrica", "wheeler-dv": "graficos-control"},
    "12.11": {"kaushik": "multiplicidad", "kohavi": "metricas-sustitutas", "provost": "asociacion-causalidad", "binet-field": "corto-largo"},
    "12.12": {"chaffey": "omnicanal", "dixon-effort": "canal-preferido", "diorio": "modelo-datos", "flint": "migracion-clientes"},
    "12.13": {"chaffey": "planificacion", "weinberg-traction": "50-50", "croll-yoskovitz": "linea-trazada", "binet-field": "share-of-voice"},
    "12.14": {"chaffey": "gobierno-digital", "kaushik": "10-90", "laja": "falsos-positivos", "enge-seo": "arquitectura"},

    # ---------------------------------------------------------------- Parte 13
    "13.01": {"pulizzi": "audiencia-primero", "handley": "utilidad", "godin": "permiso", "binet-field": "corto-largo"},
    "13.02": {"pulizzi": "nicho-contenido", "godin": "publico-minimo", "handley": "empatia", "keller-brand": "cbbe"},
    "13.03": {"sugarman": "resbaladilla", "ogilvy": "titular", "heath": "succes", "cialdini": "compromiso"},
    "13.04": {"sugarman": "semillas-curiosidad", "cialdini": "escasez", "heath": "concrecion", "handley": "edicion"},
    "13.05": {"sugarman": "justificacion", "ogilvy": "oferta-clara", "handley": "utilidad", "heath": "concrecion"},
    "13.06": {"ogilvy": "titular", "sugarman": "coherencia-promesa", "handley": "edicion", "kohavi": "twyman"},
    "13.07": {"eisenberg": "escenarios", "laja": "jerarquia-mensaje", "krug": "no-pensar", "cialdini": "compromiso"},
    "13.08": {"laja": "jerarquia-mensaje", "eisenberg": "friccion-formulario", "handley": "empatia", "krug": "escaneo"},
    "13.09": {"handley": "utilidad", "sugarman": "resbaladilla", "godin": "permiso", "chaffey": "medios-propios"},
    "13.10": {"ellet": "argumento", "dixon-customer": "habilitar", "handley": "estandar-editorial", "heath": "credibilidad"},
    "13.11": {"heath": "credibilidad", "ellet": "evidencia-caso", "handley": "estandar-editorial", "ogilvy": "investigacion"},
    "13.12": {"cialdini": "prueba-social", "sharp2": "situaciones-compra", "godin": "permiso", "reichheld": "nps-uso"},
    "13.13": {"handley": "edicion", "kohavi": "detencion-temprana", "sugarman": "coherencia-promesa", "laja": "potencia"},
    "13.14": {"handley": "estandar-editorial", "pulizzi": "consistencia", "godin": "cambio", "wheeler": "gobierno"},

    # ---------------------------------------------------------------- Parte 14
    "14.01": {"geddes": "subasta", "kaushik": "so-what", "chaffey": "modelo-canal", "ogilvy": "investigacion"},
    "14.02": {"geddes": "calidad", "kaushik": "plan-medicion", "chaffey": "planificacion", "provost": "formulacion"},
    "14.03": {"geddes": "coincidencia", "kaushik": "segmentacion", "chaffey": "medios-propios", "oneil": "proxy"},
    "14.04": {"ogilvy": "titular", "sharp2": "activos-distintivos", "binet-field": "corto-largo", "geddes": "calidad"},
    "14.05": {"geddes": "estructura-cuenta", "kaushik": "segmentacion", "chaffey": "modelo-canal", "enge-seo": "intencion"},
    "14.06": {"geddes": "subasta", "sharp2": "situaciones-compra", "kaushik": "multiplicidad", "binet-field": "60-40"},
    "14.07": {"geddes": "coincidencia", "chaffey": "modelo-canal", "dixon-customer": "consenso", "kaushik": "vanidad"},
    "14.08": {"kaushik": "so-what", "binet-field": "share-of-voice", "wheeler-dv": "comparar-dos-puntos", "geddes": "estructura-cuenta"},
    "14.09": {"kaushik": "vanidad", "geddes": "subasta", "croll-yoskovitz": "una-metrica", "chaffey": "modelo-canal"},
    "14.10": {"croll-yoskovitz": "modelos", "kaushik": "plan-medicion", "kohavi": "metricas-sustitutas", "provost": "valor-esperado"},
    "14.11": {"kaushik": "multiplicidad", "provost": "asociacion-causalidad", "kohavi": "confianza", "chaffey": "gobierno-digital"},
    "14.12": {"wheeler-dv": "variacion-comun", "kohavi": "detencion-temprana", "geddes": "calidad", "kaushik": "segmentacion"},
    "14.13": {"oneil": "auditoria", "kaushik": "so-what", "nist-airmf": "contexto", "chaffey": "gobierno-digital"},
    "14.14": {"kaushik": "plan-medicion", "geddes": "estructura-cuenta", "binet-field": "metricas-sesgo", "wheeler-dv": "graficos-control"},

    # ---------------------------------------------------------------- Parte 15
    "15.01": {"flint": "valor-canal", "croll-yoskovitz": "modelos", "chaffey": "planificacion", "fader": "heterogeneidad"},
    "15.02": {"krug": "jerarquia-visual", "flint": "migracion-clientes", "eisenberg": "escenarios", "chaffey": "omnicanal"},
    "15.03": {"krug": "no-pensar", "eisenberg": "hipotesis-cro", "laja": "jerarquia-mensaje", "dixon-effort": "esfuerzo"},
    "15.04": {"krug": "escaneo", "laja": "investigacion-previa", "eisenberg": "friccion-formulario", "flint": "recompra"},
    "15.05": {"flint": "valor-canal", "chaffey": "gobierno-digital", "croll-yoskovitz": "modelos", "krug": "no-pensar"},
    "15.06": {"dixon-effort": "resolucion-siguiente", "flint": "recompra", "chaffey": "omnicanal", "grove": "indicadores-adelantados"},
    "15.07": {"laja": "investigacion-previa", "eisenberg": "escenarios", "kaushik": "segmentacion", "krug": "prueba-usabilidad"},
    "15.08": {"laja": "falsos-positivos", "kohavi": "guardarrailes", "flint": "recompra", "chaffey": "omnicanal"},
    "15.09": {"ramanujam": "empaquetado", "flint": "recompra", "fader": "rfm", "nagle": "segmentacion-precio"},
    "15.10": {"fader": "rfm", "flint": "migracion-clientes", "cialdini": "reciprocidad", "laja": "jerarquia-mensaje"},
    "15.11": {"flint": "valor-canal", "chaffey": "modelo-canal", "porter": "cinco-fuerzas", "nagle": "cascada"},
    "15.12": {"dixon-effort": "esfuerzo", "reichheld": "cierre-circuito", "flint": "recompra", "mehta": "resultado-cliente"},
    "15.13": {"fader": "centricidad", "croll-yoskovitz": "modelos", "flint": "recompra", "fader-ltv": "cohortes-valor"},
    "15.14": {"croll-yoskovitz": "linea-trazada", "flint": "valor-canal", "provost": "valor-esperado", "hubbard": "calibracion"},

    # ---------------------------------------------------------------- Parte 16
    "16.01": {"roberge": "metricas-coaching", "diorio": "modelo-datos", "grove": "apalancamiento", "provost": "formulacion"},
    "16.02": {"roberge": "proceso-comprador", "miller-heiman": "plan-cuenta", "grove": "indicadores-adelantados", "provost": "evaluacion"},
    "16.03": {"roberge": "formacion", "miller-heiman": "senal-alerta", "grove": "indicadores-adelantados", "keenan": "diagnostico"},
    "16.04": {"diorio": "definiciones", "roberge": "proceso-comprador", "provost": "formulacion", "ross": "tipos-lead"},
    "16.05": {"diorio": "modelo-datos", "provost": "fuga-datos", "roberge": "metricas-coaching", "oneil": "proxy"},
    "16.06": {"grove": "indicadores-adelantados", "roberge": "metricas-coaching", "blount": "disciplina", "zoltners": "incentivos"},
    "16.07": {"roberge": "metricas-coaching", "grove": "indicadores-adelantados", "provost": "evaluacion", "wheeler-dv": "comparar-dos-puntos"},
    "16.08": {"zoltners": "cuotas", "roberge": "contratacion-datos", "grove": "output-gerencial", "collins": "personas-primero"},
    "16.09": {"roberge": "contratacion-datos", "zoltners": "territorios", "grove": "apalancamiento", "ross": "especializacion"},
    "16.10": {"roberge": "proceso-comprador", "grove": "apalancamiento", "croll-yoskovitz": "una-metrica", "miller-heiman": "plan-cuenta"},
    "16.11": {"kaushik": "so-what", "grove": "indicadores-adelantados", "kaplan-norton": "indicadores-causales", "wheeler-dv": "graficos-control"},
    "16.12": {"grove": "reuniones", "roberge": "metricas-coaching", "miller-heiman": "senal-alerta", "lencioni": "conflicto"},
    "16.13": {"diorio": "definiciones", "grove": "delegacion", "nist-airmf": "gobernar", "roberge": "formacion"},
    "16.14": {"roberge": "demanda", "diorio": "sistema-ingresos", "grove": "output-gerencial", "zoltners": "territorios"},

    # ---------------------------------------------------------------- Parte 17
    "17.01": {"diorio": "friccion", "grove": "apalancamiento", "nist-airmf": "funciones", "roberge": "proceso-comprador"},
    "17.02": {"diorio": "definiciones", "roberge": "demanda", "croll-yoskovitz": "etapas", "provost": "formulacion"},
    "17.03": {"provost": "evaluacion", "roberge": "metricas-coaching", "diorio": "modelo-datos", "oneil": "proxy"},
    "17.04": {"roberge": "demanda", "diorio": "friccion", "ross": "especializacion", "grove": "delegacion"},
    "17.05": {"handley": "utilidad", "godin": "permiso", "diorio": "friccion", "chaffey": "modelo-canal"},
    "17.06": {"diorio": "friccion", "grove": "delegacion", "nist-airmf": "funciones", "provost": "formulacion"},
    "17.07": {"diorio": "definiciones", "roberge": "demanda", "grove": "output-gerencial", "lencioni": "accountability"},
    "17.08": {"diorio": "modelo-datos", "provost": "formulacion", "roberge": "metricas-coaching", "kaplan-norton": "traduccion"},
    "17.09": {"diorio": "modelo-datos", "provost": "fuga-datos", "grove": "indicadores-adelantados", "nist-airmf": "gobernar"},
    "17.10": {"diorio": "sistema-ingresos", "croll-yoskovitz": "etapas", "mehta": "expansion", "kaplan-norton": "mapa-estrategico"},
    "17.11": {"mehta": "expansion", "diorio": "definiciones", "croll-yoskovitz": "cohortes", "provost": "evaluacion"},
    "17.12": {"grove": "indicadores-adelantados", "nist-airmf": "caracteristicas", "diorio": "friccion", "wheeler-dv": "variacion-comun"},
    "17.13": {"nist-airmf": "gobernar", "diorio": "definiciones", "iso-31000": "proceso", "oneil": "auditoria"},
    "17.14": {"diorio": "sistema-ingresos", "roberge": "formacion", "kaplan-norton": "cuatro-perspectivas", "grove": "output-gerencial"},

    # ---------------------------------------------------------------- Parte 18
    "18.01": {"dixon-effort": "esfuerzo", "reichheld": "proposito", "krug": "no-pensar", "mehta": "resultado-cliente"},
    "18.02": {"hulick": "primer-exito", "mehta": "leyes", "cagan": "descubrimiento", "dixon-effort": "canal-preferido"},
    "18.03": {"hulick": "carga-cognitiva", "mehta": "segmentacion-cs", "croll-yoskovitz": "una-metrica", "cagan": "resultado-output"},
    "18.04": {"mehta": "resultado-cliente", "fader": "heterogeneidad", "reichheld": "cliente-ganado", "dixon-effort": "esfuerzo"},
    "18.05": {"mehta": "salud", "provost": "evaluacion", "fader": "rfm", "croll-yoskovitz": "cohortes"},
    "18.06": {"reichheld": "nps-uso", "dixon-effort": "esfuerzo", "mehta": "salud", "malhotra": "escalas"},
    "18.07": {"mehta": "leyes", "fader": "heterogeneidad", "croll-yoskovitz": "cohortes", "reichheld": "cierre-circuito"},
    "18.08": {"fader": "centricidad", "mehta": "salud", "croll-yoskovitz": "etapas", "ellis-brown": "must-have"},
    "18.09": {"croll-yoskovitz": "cohortes", "fader": "rfm", "provost": "asociacion-causalidad", "kaushik": "segmentacion"},
    "18.10": {"mehta": "expansion", "reichheld": "cierre-circuito", "fader-ltv": "ltv-modelo", "dixon-effort": "resolucion-siguiente"},
    "18.11": {"mehta": "expansion", "fader-ltv": "inversion-diferencial", "croll-yoskovitz": "modelos", "reichheld": "cliente-ganado"},
    "18.12": {"reichheld": "cliente-ganado", "cialdini": "reciprocidad", "mehta": "leyes", "godin": "permiso"},
    "18.13": {"portigal": "conducir", "mehta": "salud", "dixon-effort": "lenguaje", "reichheld": "cierre-circuito"},
    "18.14": {"mehta": "segmentacion-cs", "fader-ltv": "cohortes-valor", "reichheld": "proposito", "croll-yoskovitz": "una-metrica"},

    # ---------------------------------------------------------------- Parte 19
    "19.01": {"ellis-brown": "equipo-multifuncional", "ries-lean": "construir-medir", "cagan": "descubrimiento", "croll-yoskovitz": "etapas"},
    "19.02": {"ellis-brown": "aha", "croll-yoskovitz": "una-metrica", "doerr": "foco", "kaplan-norton": "indicadores-causales"},
    "19.03": {"croll-yoskovitz": "etapas", "ellis-brown": "ciclo", "kaushik": "segmentacion", "bush-plg": "moment-value"},
    "19.04": {"ellis-brown": "ciclo", "bush-plg": "autoservicio", "croll-yoskovitz": "modelos", "weinberg-traction": "canales"},
    "19.05": {"ellis-brown": "aha", "hulick": "primer-exito", "croll-yoskovitz": "cohortes", "kohavi": "efecto-minimo"},
    "19.06": {"ellis-brown": "must-have", "fader": "centricidad", "croll-yoskovitz": "una-metrica", "mehta": "salud"},
    "19.07": {"reichheld": "cliente-ganado", "ellis-brown": "ciclo", "cialdini": "reciprocidad", "godin": "permiso"},
    "19.08": {"ellis-brown": "aha", "bush-plg": "autoservicio", "weinberg-traction": "canales", "godin": "cambio"},
    "19.09": {"ellis-brown": "backlog", "kohavi": "confianza", "ries-lean": "aprendizaje-validado", "cagan": "riesgos"},
    "19.10": {"ellis-brown": "ciclo", "hubbard": "calibracion", "cagan": "resultado-output", "provost": "valor-esperado"},
    "19.11": {"kohavi": "efecto-minimo", "provost": "evaluacion", "laja": "potencia", "wheeler-dv": "variacion-comun"},
    "19.12": {"kohavi": "confianza", "ellis-brown": "ciclo", "cagan": "descubrimiento", "provost": "formulacion"},
    "19.13": {"bush-plg": "autoservicio", "ellis-brown": "must-have", "cagan": "resultado-output", "croll-yoskovitz": "modelos"},
    "19.14": {"ellis-brown": "ciclo", "croll-yoskovitz": "modelos", "provost": "valor-esperado", "kohavi": "guardarrailes"},

    # ---------------------------------------------------------------- Parte 20
    "20.01": {"kaplan-norton": "mapa-estrategico", "croll-yoskovitz": "una-metrica", "provost": "formulacion", "kaushik": "so-what"},
    "20.02": {"kaushik": "segmentacion", "croll-yoskovitz": "etapas", "provost": "evaluacion", "wheeler-dv": "comparar-dos-puntos"},
    "20.03": {"croll-yoskovitz": "modelos", "provost": "valor-esperado", "fader-ltv": "cohortes-valor", "kaushik": "plan-medicion"},
    "20.04": {"fader-ltv": "ltv-modelo", "fader": "heterogeneidad", "provost": "sobreajuste", "croll-yoskovitz": "cohortes"},
    "20.05": {"croll-yoskovitz": "linea-trazada", "fader-ltv": "inversion-diferencial", "provost": "valor-esperado", "simon": "palanca-precio"},
    "20.06": {"croll-yoskovitz": "modelos", "provost": "formulacion", "nagle": "costo-piso", "simon": "valor-percibido"},
    "20.07": {"croll-yoskovitz": "cohortes", "fader": "rfm", "provost": "asociacion-causalidad", "kaushik": "segmentacion"},
    "20.08": {"kaushik": "multiplicidad", "kohavi": "metricas-sustitutas", "provost": "asociacion-causalidad", "binet-field": "corto-largo"},
    "20.09": {"kohavi": "guardarrailes", "provost": "valor-esperado", "kaushik": "so-what", "binet-field": "metricas-sesgo"},
    "20.10": {"kohavi": "efecto-minimo", "provost": "sobreajuste", "laja": "potencia", "wheeler-dv": "variacion-comun"},
    "20.11": {"wheeler-dv": "graficos-control", "provost": "evaluacion", "hubbard": "calibracion", "croll-yoskovitz": "cohortes"},
    "20.12": {"provost": "asociacion-causalidad", "kohavi": "confianza", "binet-field": "corto-largo", "hubbard": "medicion-definicion"},
    "20.13": {"kaplan-norton": "cuatro-perspectivas", "wheeler-dv": "comparar-dos-puntos", "kaushik": "so-what", "grove": "indicadores-adelantados"},
    "20.14": {"provost": "formulacion", "croll-yoskovitz": "linea-trazada", "kohavi": "twyman", "hubbard": "valor-informacion"},

    # ---------------------------------------------------------------- Parte 21
    "21.01": {"russell-norvig": "agente-racional", "nist-airmf": "funciones", "provost": "formulacion", "ng-mlyearning": "metrica-unica"},
    "21.02": {"ng-mlyearning": "conjunto-evaluacion", "nist-airmf": "contexto", "handley": "utilidad", "russell-norvig": "medida-desempeno"},
    "21.03": {"ng-mlyearning": "diagnostico", "oneil": "armas", "hubbard": "valor-informacion", "provost": "evaluacion"},
    "21.04": {"handley": "estandar-editorial", "nist-airmf": "gobernar", "oneil": "auditoria", "godin": "permiso"},
    "21.05": {"thaler": "arquitectura-decision", "oneil": "proxy", "nist-airmf": "contexto", "cialdini": "reciprocidad"},
    "21.06": {"blount": "bloques", "nist-airmf": "caracteristicas", "oneil": "retroalimentacion", "provost": "fuga-datos"},
    "21.07": {"provost": "sobreajuste", "ng-mlyearning": "diagnostico", "oneil": "retroalimentacion", "nist-airmf": "caracteristicas"},
    "21.08": {"nist-airmf": "caracteristicas", "roberge": "formacion", "ng-mlyearning": "conjunto-evaluacion", "rackham": "avance"},
    "21.09": {"russell-norvig": "agente-racional", "nist-airmf": "gobernar", "iso-31000": "riesgo-residual", "oneil": "auditoria"},
    "21.10": {"nist-airmf": "contexto", "provost": "asociacion-causalidad", "rackham": "implicacion", "roberge": "metricas-coaching"},
    "21.11": {"mehta": "salud", "dixon-effort": "resolucion-siguiente", "provost": "evaluacion", "nist-airmf": "caracteristicas"},
    "21.12": {"nist-airmf": "funciones", "ng-mlyearning": "conjunto-evaluacion", "kohavi": "guardarrailes", "iso-31000": "proceso"},
    "21.13": {"nist-airmf": "gobernar", "oneil": "auditoria", "iso-31000": "riesgo-residual", "russell-norvig": "entorno"},
    "21.14": {"nist-airmf": "funciones", "iso-31000": "principios", "russell-norvig": "medida-desempeno", "diorio": "sistema-ingresos"},

    # ---------------------------------------------------------------- Parte 22
    "22.01": {"moore": "producto-completo", "rumelt": "nucleo", "bush-plg": "autoservicio", "ross": "especializacion"},
    "22.02": {"moore": "beachhead", "porter": "cinco-fuerzas", "rumelt": "diagnostico", "blank": "hipotesis"},
    "22.03": {"moore": "referencias", "rumelt": "foco", "godin": "publico-minimo", "porter-hbr": "renuncia"},
    "22.04": {"ross": "pipeline-predecible", "roberge": "contratacion-datos", "zoltners": "cuotas", "moore": "abismo"},
    "22.05": {"bush-plg": "moment-value", "cagan": "resultado-output", "ellis-brown": "must-have", "croll-yoskovitz": "modelos"},
    "22.06": {"moore": "producto-completo", "weinberg-traction": "canales", "porter": "excedente", "ross": "tipos-lead"},
    "22.07": {"moore": "ciclo-adopcion", "porter": "grupos-estrategicos", "nagle": "segmentacion-precio", "weinberg-traction": "bullseye"},
    "22.08": {"nagle": "cascada", "moore": "producto-completo", "croll-yoskovitz": "modelos", "porter": "excedente"},
    "22.09": {"moore": "abismo", "cagan": "riesgos", "roberge": "formacion", "handley": "estandar-editorial"},
    "22.10": {"moore": "referencias", "porter": "cinco-fuerzas", "rumelt": "foco", "blank": "fuera-del-edificio"},
    "22.11": {"moore": "ciclo-adopcion", "christensen": "circunstancia", "rumelt": "diagnostico", "cagan": "descubrimiento"},
    "22.12": {"porter": "grupos-estrategicos", "moore": "producto-completo", "rumelt": "foco", "iso-31000": "proceso"},
    "22.13": {"croll-yoskovitz": "una-metrica", "ross": "pipeline-predecible", "bush-plg": "ocasion-upgrade", "kaplan-norton": "indicadores-causales"},
    "22.14": {"moore": "beachhead", "rumelt": "nucleo", "ross": "especializacion", "weinberg-traction": "bullseye"},

    # ---------------------------------------------------------------- Parte 23
    "23.01": {"ross": "especializacion", "roberge": "contratacion-datos", "grove": "output-gerencial", "zoltners": "territorios"},
    "23.02": {"grove": "delegacion", "lencioni": "accountability", "zoltners": "incentivos", "roberge": "formacion"},
    "23.03": {"roberge": "contratacion-datos", "collins": "personas-primero", "zoltners": "cuotas", "lencioni": "confianza"},
    "23.04": {"roberge": "formacion", "ericsson": "practica-deliberada", "grove": "delegacion", "ambrose": "practica-feedback"},
    "23.05": {"zoltners": "incentivos", "grove": "output-gerencial", "roberge": "metricas-coaching", "collins": "disciplina"},
    "23.06": {"grove": "apalancamiento", "doerr": "foco", "kaplan-norton": "traduccion", "croll-yoskovitz": "linea-trazada"},
    "23.07": {"doerr": "okr", "grove": "indicadores-adelantados", "kaplan-norton": "indicadores-causales", "collins": "disciplina"},
    "23.08": {"grove": "output-gerencial", "roberge": "metricas-coaching", "wheeler-dv": "graficos-control", "kaplan-norton": "traduccion"},
    "23.09": {"grove": "reuniones", "lencioni": "conflicto", "doerr": "seguimiento", "collins": "hechos-brutales"},
    "23.10": {"ericsson": "practica-deliberada", "roberge": "metricas-coaching", "grove": "delegacion", "rackham": "spin"},
    "23.11": {"grove": "output-gerencial", "zoltners": "territorios", "lencioni": "accountability", "collins": "personas-primero"},
    "23.12": {"lencioni": "confianza", "collins": "disciplina", "cialdini": "escasez", "oneil": "armas"},
    "23.13": {"grove": "reuniones", "kaplan-norton": "cuatro-perspectivas", "collins": "hechos-brutales", "doerr": "transparencia"},
    "23.14": {"grove": "apalancamiento", "doerr": "seguimiento", "collins": "erizo", "kaplan-norton": "mapa-estrategico"},

    # ---------------------------------------------------------------- Parte 24
    "24.01": {"osterwalder-bmg": "nueve-bloques", "rumelt": "nucleo", "ellet": "tipos-caso", "blank": "hipotesis"},
    "24.02": {"blank": "customer-discovery", "christensen": "job", "moore": "beachhead", "fitzpatrick": "mom-test"},
    "24.03": {"fitzpatrick": "compromiso", "malhotra": "diseno-investigacion", "portigal": "conducir", "hubbard": "valor-informacion"},
    "24.04": {"ramanujam": "precio-primero", "nagle": "valor-diferencial", "croll-yoskovitz": "modelos", "simon": "palanca-precio"},
    "24.05": {"ries-trout": "mente", "wheeler": "aplicabilidad", "handley": "estandar-editorial", "keller-brand": "paridad-diferencia"},
    "24.06": {"moore": "producto-completo", "ross": "pipeline-predecible", "bush-plg": "autoservicio", "rumelt": "foco"},
    "24.07": {"geddes": "estructura-cuenta", "kaushik": "plan-medicion", "laja": "investigacion-previa", "handley": "utilidad"},
    "24.08": {"weinberg-sales": "lista-objetivo", "blount": "disciplina", "rackham": "spin", "ross": "especializacion"},
    "24.09": {"roberge": "proceso-comprador", "diorio": "modelo-datos", "grove": "indicadores-adelantados", "provost": "formulacion"},
    "24.10": {"mehta": "resultado-cliente", "hulick": "primer-exito", "fader-ltv": "ltv-modelo", "dixon-effort": "esfuerzo"},
    "24.11": {"kaplan-norton": "cuatro-perspectivas", "croll-yoskovitz": "linea-trazada", "provost": "evaluacion", "kaushik": "so-what"},
    "24.12": {"iso-31000": "proceso", "oneil": "auditoria", "nist-airmf": "gobernar", "rumelt": "diagnostico"},
    "24.13": {"ellet": "argumento", "heath": "maldicion-conocimiento", "rumelt": "mala-estrategia", "grove": "reuniones"},
    "24.14": {"ellet": "evidencia-caso", "ericsson": "representaciones", "ambrose": "motivacion", "wiggins": "diseno-inverso"},
}


def anclaje(parte, clase):
    """Devuelve el mapa {obra: identificador} de una clase."""
    return ANCLAJES.get("{}.{}".format(parte, clase), {})


def total_anclajes():
    return sum(len(v) for v in ANCLAJES.values())
