# -*- coding: utf-8 -*-
"""Aportes concretos de cada obra de la bibliografía.

El «lente» de `bibliografia.py` describe para qué sirve una obra en general.
Eso no basta para fundamentar una clase: si *Data Science for Business* se cita
en cincuenta clases con la misma frase, la cita es decorativa.

Este catálogo registra, para cada obra, las **ideas concretas** que aporta:
tesis, marcos, distinciones o hallazgos identificables dentro del texto. Cada
clase ancla una de ellas mediante `anclas=[(clave_obra, identificador), ...]`,
de modo que el material declara *qué* de esa obra sostiene *este* contenido.

Formato: clave de obra -> {identificador: (idea, dónde buscarla)}

- **idea**: enunciado de la aportación, redactado para poder citarse en clase.
- **dónde buscarla**: pista de lectura selectiva. Se describe por su nombre en
  la obra —capítulo, parte o concepto— y **nunca por número de página**, que
  varía entre ediciones y no podríamos garantizar.
"""

APORTES = {
    # ================================================================ MARKETING Y ESTRATEGIA
    "kotler": {
        "stp": ("la secuencia segmentación → targeting → posicionamiento como decisión previa a la mezcla comercial",
                "los capítulos sobre identificación de segmentos y posicionamiento de marca"),
        "mezcla": ("la mezcla comercial como sistema de decisiones interdependientes y no como lista de palancas",
                   "la parte dedicada al diseño de la oferta y sus capítulos de producto, precio, plaza y promoción"),
        "demanda": ("los estados de la demanda y la tarea del marketing en cada uno, incluida la demanda negativa",
                    "el capítulo introductorio sobre el alcance del marketing"),
        "valor-cliente": ("el valor percibido como diferencia entre beneficio total y costo total para el cliente",
                          "el capítulo sobre creación de valor y satisfacción del cliente"),
        "canales": ("el canal como sistema que cumple funciones de información, transacción y servicio",
                    "los capítulos sobre diseño y gestión de canales de marketing"),
        "ciclo-vida": ("las decisiones de marketing que corresponden a cada fase del ciclo de vida del producto",
                       "el capítulo sobre estrategias a lo largo del ciclo de vida"),
    },
    "sharp": {
        "penetracion": ("la ley de doble riesgo: las marcas pequeñas tienen menos compradores y además compran menos",
                        "los capítulos sobre las leyes empíricas del crecimiento de marcas"),
        "disponibilidad": ("disponibilidad mental y física como los dos motores del crecimiento",
                           "el capítulo dedicado a la disponibilidad como mecanismo"),
        "compradores-ligeros": ("el peso de los compradores ocasionales en el volumen total, frente al mito de la lealtad",
                                "el capítulo sobre la distribución de la frecuencia de compra"),
        "diferenciacion": ("la evidencia de que las marcas de una categoría comparten compradores y se diferencian menos de lo que creen",
                           "el capítulo que contrasta diferenciación y distintividad"),
        "alcance": ("el alcance amplio frente a la segmentación estrecha como estrategia de crecimiento",
                    "los capítulos sobre cómo crecen realmente las marcas"),
    },
    "sharp2": {
        "activos-distintivos": ("los activos distintivos de marca y su medición por asociación única",
                                "el capítulo sobre construcción y medición de activos distintivos"),
        "estructuras-memoria": ("las estructuras de memoria como objeto real de la construcción de marca",
                                "los capítulos sobre memoria y recuerdo de marca"),
        "situaciones-compra": ("las situaciones de compra como puntos de entrada a la memoria de categoría",
                               "el capítulo sobre puntos de entrada de categoría"),
        "consistencia": ("la consistencia sostenida como condición para que un activo se vuelva distintivo",
                         "el capítulo sobre gestión de activos en el tiempo"),
    },
    "binet-field": {
        "60-40": ("la proporción entre inversión en construcción de marca y en activación de ventas",
                  "la sección sobre asignación óptima del presupuesto"),
        "corto-largo": ("los efectos de corto plazo decaen; los de marca se acumulan y bajan la elasticidad de precio",
                        "los capítulos sobre curvas de respuesta en el tiempo"),
        "metricas-sesgo": ("el sesgo de las métricas de corto plazo hacia la activación y su efecto sobre el presupuesto",
                           "la discusión sobre medición y horizonte temporal"),
        "share-of-voice": ("la relación entre participación de voz y crecimiento de participación de mercado",
                           "la sección sobre exceso de participación de voz"),
    },
    "ries-trout": {
        "mente": ("el posicionamiento ocurre en la mente del prospecto, no en el producto",
                  "los capítulos iniciales sobre qué es el posicionamiento"),
        "escalera": ("la escalera de categoría: las marcas ocupan peldaños y desplazar al líder es caro",
                     "el capítulo sobre la escalera del producto"),
        "primero": ("la ventaja de ser primero en una categoría frente a ser mejor en una existente",
                    "los capítulos sobre liderazgo de categoría"),
        "reposicionar": ("el reposicionamiento de la competencia como movimiento explícito",
                         "el capítulo sobre reposicionamiento"),
        "nombre": ("el nombre como primer acto de posicionamiento y su efecto en la extensión futura",
                   "los capítulos sobre nombre y trampa de la extensión de línea"),
    },
    "porter": {
        "cinco-fuerzas": ("las cinco fuerzas que determinan la rentabilidad estructural de una industria",
                          "el capítulo sobre análisis estructural de industrias"),
        "grupos-estrategicos": ("los grupos estratégicos y las barreras de movilidad entre ellos",
                                "el capítulo sobre mapas de grupos estratégicos"),
        "senales": ("las señales de mercado y cómo se leen los movimientos del competidor",
                    "el capítulo sobre señales del mercado"),
        "competidor": ("el análisis del competidor por sus objetivos, supuestos y capacidades, no por su catálogo",
                       "el capítulo sobre análisis de la competencia"),
        "excedente": ("la distribución del excedente entre proveedores, competidores y compradores",
                      "los capítulos sobre poder de negociación"),
    },
    "porter-hbr": {
        "eficacia-vs-estrategia": ("la eficacia operativa no es estrategia: alcanzar la frontera de las mejores prácticas no diferencia",
                                   "la primera sección del artículo"),
        "encaje": ("el encaje entre actividades como fuente de ventaja difícil de imitar",
                   "la sección sobre el encaje de actividades"),
        "renuncia": ("la elección estratégica implica renunciar deliberadamente a opciones",
                     "la sección sobre trade-offs"),
    },
    "rumelt": {
        "nucleo": ("el núcleo de una estrategia: diagnóstico, política rectora y acción coherente",
                   "la parte sobre el núcleo de la buena estrategia"),
        "mala-estrategia": ("los signos de la mala estrategia: palabrería, ausencia de diagnóstico y objetivos que no eligen",
                            "los capítulos sobre mala estrategia"),
        "diagnostico": ("el diagnóstico como reformulación del problema que hace evidente la acción",
                        "el capítulo sobre el diagnóstico"),
        "foco": ("la concentración de recursos en un punto donde produzcan efecto desproporcionado",
                 "los capítulos sobre foco y palanca"),
    },
    "kim-mauborgne": {
        "curva-valor": ("la curva de valor como comparación explícita de atributos frente a la industria",
                        "el capítulo sobre el lienzo estratégico"),
        "eliminar-crear": ("el esquema de eliminar, reducir, incrementar y crear atributos",
                           "el capítulo sobre el marco de las cuatro acciones"),
        "no-clientes": ("los no clientes como fuente de crecimiento por encima de la competencia por los actuales",
                        "el capítulo sobre los tres niveles de no clientes"),
    },
    "moore": {
        "abismo": ("el abismo entre visionarios y pragmáticos y por qué las referencias no cruzan solas",
                   "los capítulos centrales sobre el abismo"),
        "beachhead": ("el mercado cabeza de playa elegido por dominancia alcanzable y no por tamaño",
                      "el capítulo sobre selección del mercado objetivo"),
        "producto-completo": ("el producto completo: lo que el pragmático necesita además del producto central",
                              "el capítulo sobre el producto completo"),
        "referencias": ("las referencias dentro del mismo segmento como mecanismo de adopción",
                        "los capítulos sobre segmentación y referencias"),
        "ciclo-adopcion": ("el ciclo de adopción tecnológica y las discontinuidades entre grupos",
                           "el capítulo introductorio sobre el ciclo de adopción"),
    },
    "drucker": {
        "crear-cliente": ("el propósito de una empresa es crear un cliente, y por eso sólo marketing e innovación producen resultados",
                          "el capítulo sobre el propósito del negocio"),
        "cual-es-el-negocio": ("la pregunta «¿cuál es nuestro negocio?» respondida desde el cliente y no desde el producto",
                               "los capítulos sobre la definición del negocio"),
        "objetivos": ("los objetivos como compromisos en áreas clave, no como aspiraciones",
                      "la parte sobre dirección por objetivos"),
    },
    "levitt": {
        "miopia": ("las industrias declinan cuando se definen por el producto que fabrican y no por la necesidad que sirven",
                   "la tesis central del artículo"),
        "definicion-negocio": ("la redefinición del negocio en términos del trabajo del cliente",
                               "los ejemplos de ferrocarriles y cine"),
    },

    # ================================================================ CLIENTE E INVESTIGACIÓN
    "christensen": {
        "job": ("el trabajo que el cliente contrata: el progreso que intenta lograr en una circunstancia",
                "los capítulos sobre la teoría del trabajo por hacer"),
        "circunstancia": ("la circunstancia como unidad de análisis, por encima del perfil demográfico",
                          "el capítulo sobre circunstancias y no clientes"),
        "contratar-despedir": ("la lógica de contratar y despedir soluciones para un mismo trabajo",
                               "los capítulos sobre competencia por el trabajo"),
        "dimensiones": ("las dimensiones funcional, social y emocional de un mismo trabajo",
                        "el capítulo sobre la complejidad del trabajo"),
        "milkshake": ("el caso del batido: el mismo producto sirve trabajos distintos según el momento",
                      "el capítulo que introduce el caso del batido matinal"),
    },
    "ulwick": {
        "resultados": ("los resultados deseados formulados como enunciados medibles con dirección y unidad",
                       "los capítulos sobre declaraciones de resultado deseado"),
        "oportunidad": ("la puntuación de oportunidad que combina importancia e insatisfacción",
                        "el capítulo sobre el algoritmo de oportunidad"),
        "mapa-job": ("el mapa del trabajo por etapas, desde la definición hasta la conclusión",
                     "el capítulo sobre el mapeo del trabajo"),
        "segmentacion-outcome": ("la segmentación por resultados desatendidos en lugar de por demografía",
                                 "los capítulos sobre segmentación basada en resultados"),
    },
    "fitzpatrick": {
        "mom-test": ("preguntar por comportamiento pasado y hechos concretos en lugar de opiniones sobre el futuro",
                     "el capítulo que enuncia la regla"),
        "compromiso": ("el compromiso costoso —tiempo, dinero o reputación— como única señal fiable de interés",
                       "los capítulos sobre compromiso y avance"),
        "elogios": ("los elogios como ruido: la conversación que sólo produce entusiasmo no produjo información",
                    "el capítulo sobre malas conversaciones"),
        "preguntas-malas": ("las preguntas que garantizan una respuesta inútil por su formulación",
                            "los capítulos sobre preguntas correctas e incorrectas"),
    },
    "portigal": {
        "conducir": ("la conducción de la entrevista: silencio, repregunta y renuncia a completar la respuesta",
                     "los capítulos sobre técnica de entrevista"),
        "sintesis": ("la síntesis desde el registro textual hasta las categorías, sin saltar a la interpretación",
                     "los capítulos sobre análisis y síntesis"),
        "sesgo-entrevistador": ("el efecto del entrevistador sobre lo que el entrevistado dice",
                                "el capítulo sobre la postura del investigador"),
    },
    "blank": {
        "customer-discovery": ("el descubrimiento de clientes como fase previa y separada de la validación",
                               "la parte dedicada al customer discovery"),
        "fuera-del-edificio": ("no hay hechos dentro del edificio: las hipótesis se contrastan afuera",
                               "los capítulos iniciales sobre el proceso"),
        "hipotesis": ("la conversión del plan de negocio en hipótesis enumeradas y comprobables",
                      "el capítulo sobre formulación de hipótesis"),
        "pivote": ("el pivote como cambio de hipótesis conservando lo aprendido",
                   "los capítulos sobre validación y pivote"),
    },
    "osterwalder-vpd": {
        "encaje": ("el encaje entre perfil del cliente y mapa de valor, verificado y no supuesto",
                   "la sección sobre el encaje problema-solución"),
        "perfil": ("el perfil del cliente en tareas, dolores y ganancias observadas",
                   "la sección sobre el perfil del cliente"),
        "mapa-valor": ("el mapa de valor: aliviadores de dolor y generadores de ganancia asociados a elementos concretos",
                       "la sección sobre el mapa de valor"),
        "prueba": ("la prueba de la propuesta antes de construir, con supuestos marcados",
                   "la parte dedicada a probar la propuesta"),
    },
    "osterwalder-bmg": {
        "nueve-bloques": ("los nueve bloques del modelo de negocio y su interdependencia",
                          "la sección que describe el lienzo"),
        "patrones": ("los patrones de modelo de negocio: plataformas, cebo y anzuelo, larga cola",
                     "la sección sobre patrones"),
        "estructura-costos": ("la distinción entre modelos guiados por costo y guiados por valor",
                              "el bloque de estructura de costos"),
    },
    "kahneman": {
        "dos-sistemas": ("los sistemas 1 y 2: la decisión rápida asociativa frente a la deliberada",
                         "la primera parte del libro"),
        "anclaje": ("el anclaje y ajuste insuficiente: la primera cifra contamina el juicio posterior",
                    "el capítulo sobre anclaje"),
        "aversion-perdida": ("la aversión a la pérdida: perder pesa más que ganar lo equivalente",
                             "los capítulos sobre teoría prospectiva"),
        "disponibilidad": ("la heurística de disponibilidad: se juzga la frecuencia por la facilidad de recordar",
                           "el capítulo sobre disponibilidad"),
        "wysiati": ("«lo que ves es todo lo que hay»: la mente construye coherencia con la información presente",
                    "el capítulo sobre la máquina de saltar a conclusiones"),
        "ilusion-validez": ("la ilusión de validez: la confianza no predice la exactitud",
                            "los capítulos sobre exceso de confianza"),
    },
    "thaler": {
        "arquitectura-decision": ("la arquitectura de la decisión: no existe presentación neutra de las opciones",
                                  "los capítulos sobre arquitectura de elección"),
        "opcion-defecto": ("la opción por defecto como la decisión más influyente del diseño",
                           "el capítulo sobre valores por defecto"),
        "sludge": ("la fricción deliberada que dificulta lo que conviene al usuario y beneficia a quien la diseña",
                   "la discusión sobre sludge en la edición final"),
        "libertario-paternalismo": ("el límite ético: orientar sin restringir la elección",
                                    "los capítulos que definen el criterio"),
    },
    "cialdini": {
        "reciprocidad": ("la reciprocidad: el aporte previo genera disposición a corresponder",
                         "el capítulo sobre reciprocidad"),
        "prueba-social": ("la prueba social funciona por similitud del referente, no por cantidad",
                          "el capítulo sobre aprobación social"),
        "compromiso": ("compromiso y coherencia: el pequeño paso previo condiciona el siguiente",
                       "el capítulo sobre compromiso y coherencia"),
        "escasez": ("la escasez como amplificador del valor percibido y su límite ético",
                    "el capítulo sobre escasez"),
        "autoridad": ("la autoridad señalizada y la diferencia entre credibilidad y apariencia",
                      "el capítulo sobre autoridad"),
        "unidad": ("la unidad: la identidad compartida como principio incorporado en la edición ampliada",
                   "el capítulo sobre unidad"),
    },
    "ariely": {
        "relatividad": ("la relatividad: la opción señuelo cambia la elección entre las otras dos",
                        "el capítulo sobre relatividad"),
        "gratis": ("el efecto de lo gratuito sobre la evaluación racional del costo-beneficio",
                   "el capítulo sobre el costo de lo gratis"),
        "precio-ancla": ("las anclas arbitrarias y su persistencia en decisiones posteriores",
                         "el capítulo sobre la coherencia arbitraria"),
        "expectativa": ("el efecto de la expectativa sobre la experiencia percibida",
                        "los capítulos sobre expectativas y precio"),
    },
    "solomon": {
        "proceso-decision": ("el proceso de decisión del consumidor y sus etapas observables",
                             "la parte sobre toma de decisiones del consumidor"),
        "grupos-referencia": ("los grupos de referencia y su influencia normativa e informativa",
                              "el capítulo sobre influencia de grupos"),
        "identidad": ("el consumo como expresión de identidad y pertenencia",
                      "los capítulos sobre el yo y el consumo"),
        "cultura": ("la cultura y la subcultura como marco de significado de la compra",
                    "la parte sobre consumidores y cultura"),
        "riesgo-percibido": ("los tipos de riesgo percibido: funcional, económico, social, físico y psicológico",
                             "el capítulo sobre decisión y riesgo"),
    },
    "malhotra": {
        "diseno-investigacion": ("la clasificación entre investigación exploratoria, descriptiva y causal",
                                 "los capítulos sobre diseño de investigación"),
        "muestreo": ("los métodos de muestreo probabilístico y no probabilístico y su efecto en la inferencia",
                     "los capítulos sobre diseño y tamaño de muestra"),
        "escalas": ("la construcción de escalas y las amenazas a la validez del constructo",
                    "los capítulos sobre medición y escalamiento"),
        "cuestionario": ("el diseño del cuestionario: orden, formulación y sesgo de respuesta",
                         "el capítulo sobre diseño de cuestionarios"),
        "error-total": ("el error total de la investigación: muestral y no muestral",
                        "el capítulo sobre fuentes de error"),
    },
    "krug": {
        "no-pensar": ("la primera ley: la página no debe obligar a pensar dónde está uno ni qué hacer",
                      "los capítulos iniciales sobre usabilidad"),
        "escaneo": ("las personas escanean, no leen: satisfacen en lugar de optimizar",
                    "el capítulo sobre cómo usamos realmente la web"),
        "prueba-usabilidad": ("la prueba de usabilidad barata con pocos usuarios como práctica regular",
                              "los capítulos sobre pruebas de usabilidad"),
        "jerarquia-visual": ("la jerarquía visual como traducción de la importancia relativa",
                             "el capítulo sobre diseño de páginas"),
    },

    # ================================================================ MARCA Y COMUNICACIÓN
    "aaker": {
        "identidad": ("la identidad de marca como conjunto aspiracional que guía decisiones internas",
                      "los capítulos sobre el sistema de identidad de marca"),
        "equity": ("los componentes del valor de marca: notoriedad, asociaciones, calidad percibida y lealtad",
                   "los capítulos sobre activos de marca"),
        "arquitectura": ("la arquitectura de marca y el costo de sostener cada marca adicional",
                         "los capítulos sobre relaciones entre marcas"),
        "posicion": ("la posición de marca como la parte de la identidad que se comunica activamente",
                     "el capítulo sobre implementación de la identidad"),
    },
    "keller-brand": {
        "cbbe": ("la pirámide de valor de marca basada en el cliente: notoriedad, significado, respuesta y resonancia",
                 "el capítulo sobre el modelo CBBE"),
        "paridad-diferencia": ("los puntos de paridad y de diferencia y el orden en que se comunican",
                               "el capítulo sobre posicionamiento de marca"),
        "resonancia": ("la resonancia como intensidad del vínculo y no como satisfacción declarada",
                       "la cúspide del modelo CBBE"),
        "medicion": ("el sistema de medición del valor de marca con fuentes y resultados",
                     "la parte sobre medición del brand equity"),
    },
    "wheeler": {
        "proceso": ("el proceso de identidad en cinco fases, desde la investigación hasta la gestión de activos",
                    "la parte sobre el proceso de identidad de marca"),
        "aplicabilidad": ("la prueba de aplicación en todos los soportes reales antes de aprobar un sistema",
                          "la sección sobre elementos y aplicaciones"),
        "gobierno": ("el gobierno de la identidad: normas, permisos y mantenimiento",
                     "la sección sobre gestión de activos"),
    },
    "heath": {
        "succes": ("las seis propiedades de las ideas que perduran: simple, inesperada, concreta, creíble, emocional y con historia",
                   "la introducción que enuncia el marco"),
        "maldicion-conocimiento": ("la maldición del conocimiento: quien sabe no puede imaginar no saber",
                                   "el capítulo introductorio y sus ejercicios"),
        "concrecion": ("la concreción como antídoto contra la abstracción que no se recuerda",
                       "el capítulo sobre concreción"),
        "credibilidad": ("la credibilidad interna mediante detalle verificable y estadísticas humanizadas",
                         "el capítulo sobre credibilidad"),
    },
    "godin": {
        "publico-minimo": ("el público mínimo viable: servir a los pocos que sí quieren esto",
                           "los capítulos sobre el público mínimo viable"),
        "permiso": ("el permiso como activo: el derecho a comunicarse con quien espera el mensaje",
                    "los capítulos sobre marketing de permiso"),
        "cambio": ("el marketing como oferta de un cambio que alguien busca, no como difusión",
                   "los capítulos iniciales sobre qué es el marketing"),
        "tension": ("la tensión productiva frente a la presión: el compromiso que produce avance",
                    "el capítulo sobre tensión"),
    },
    "handley": {
        "utilidad": ("la utilidad para el lector como criterio por encima de la elegancia del autor",
                     "la parte sobre reglas de escritura"),
        "empatia": ("la escritura desde el problema del lector y en su vocabulario",
                    "los capítulos sobre empatía con el lector"),
        "edicion": ("la edición como eliminación: el primer borrador siempre sobra",
                    "los capítulos sobre proceso de escritura"),
        "estandar-editorial": ("el estándar editorial: verificación de datos, claridad y coherencia de voz",
                               "la parte sobre publicación y estándares"),
    },
    "pulizzi": {
        "audiencia-primero": ("construir audiencia propia antes de monetizar",
                              "los capítulos sobre el modelo de contenido"),
        "nicho-contenido": ("la intersección entre lo que se sabe y lo que la audiencia necesita, llevada a un nicho estrecho",
                            "el capítulo sobre el punto dulce"),
        "consistencia": ("la consistencia sostenida durante años como condición del modelo",
                         "los capítulos sobre plataforma base y ritmo"),
        "diversificacion": ("la diversificación de canales una vez construida la audiencia propia",
                            "los capítulos sobre expansión"),
    },
    "sugarman": {
        "resbaladilla": ("la resbaladilla: cada elemento del texto sólo debe lograr que se lea el siguiente",
                         "el capítulo sobre el concepto de resbaladilla"),
        "semillas-curiosidad": ("las semillas de curiosidad que sostienen la lectura",
                                "los capítulos sobre técnicas de redacción"),
        "coherencia-promesa": ("la coherencia entre la promesa del titular y lo que entrega el cuerpo",
                               "los capítulos sobre encabezados"),
        "justificacion": ("la justificación racional de una decisión que se toma emocionalmente",
                          "los capítulos sobre disparadores psicológicos"),
    },
    "ogilvy": {
        "investigacion": ("la publicidad basada en investigación previa y no en intuición creativa",
                          "los capítulos sobre cómo producir publicidad que venda"),
        "titular": ("el titular como la parte que determina si el resto se lee",
                    "el capítulo sobre redacción de titulares"),
        "respeto": ("el respeto por el lector: no es tonto, es tu cónyuge",
                    "los capítulos sobre principios de redacción"),
        "oferta-clara": ("la oferta clara y la promesa concreta por encima del ingenio",
                         "los capítulos sobre qué hace funcionar un anuncio"),
    },

    # ================================================================ PRECIO Y MONETIZACIÓN
    "nagle": {
        "valor-diferencial": ("el valor económico: precio de referencia de la alternativa más el valor diferencial cuantificado",
                              "el capítulo sobre estimación del valor económico"),
        "cascada": ("la cascada de precio: del precio de lista al precio de bolsillo tras descuentos y concesiones",
                    "el capítulo sobre gestión del precio realizado"),
        "sensibilidad": ("los factores que aumentan o reducen la sensibilidad al precio y su gestión deliberada",
                         "el capítulo sobre sensibilidad al precio"),
        "segmentacion-precio": ("las barreras de segmentación de precio y su legitimidad ante el cliente",
                                "el capítulo sobre estructura de precios"),
        "politica": ("la política de precios como sistema de reglas que evita negociar cada caso",
                     "el capítulo sobre política y disciplina de precios"),
        "costo-piso": ("el costo como piso de decisión y no como método de fijación",
                       "el capítulo sobre costos relevantes para la decisión"),
    },
    "simon": {
        "palanca-precio": ("el precio como la palanca de utilidad más rápida frente a volumen y costo",
                           "los capítulos sobre el poder del precio"),
        "valor-percibido": ("el precio como reflejo del valor percibido y la tarea de comunicarlo",
                            "los capítulos sobre valor y precio"),
        "guerra-precios": ("la guerra de precios como resultado evitable de decisiones tácticas",
                           "los capítulos sobre competencia en precio"),
        "psicologia-precio": ("los efectos psicológicos del precio y su uso responsable",
                              "los capítulos sobre psicología del precio"),
    },
    "ramanujam": {
        "precio-primero": ("la conversación de precio antes de construir el producto",
                           "los capítulos iniciales sobre el proceso invertido"),
        "disposicion-pagar": ("las técnicas de conversación sobre disposición a pagar con clientes reales",
                              "el capítulo sobre cómo preguntar por el precio"),
        "empaquetado": ("el empaquetado desde la disposición a pagar por atributo y no desde la arquitectura técnica",
                        "el capítulo sobre configuración y empaquetado"),
        "modelo-monetizacion": ("los modelos de monetización disponibles y el criterio para elegir la métrica de cobro",
                                "el capítulo sobre modelos de monetización"),
        "fracasos": ("los cuatro tipos de fracaso de producto por decisiones de monetización tardías",
                     "el capítulo que clasifica los fracasos"),
    },
    "smith-pricing": {
        "price-fences": ("las barreras de precio que sostienen la segmentación sin arbitraje",
                         "los capítulos sobre segmentación de precios"),
        "versionado": ("el versionado como mecanismo de captura en segmentos con disposición distinta",
                       "los capítulos sobre estructura de la oferta"),
        "estructura": ("la estructura de precios como decisión separada del nivel de precio",
                       "los capítulos sobre arquitectura de precios"),
    },

    # ================================================================ VENTAS
    "rackham": {
        "implicacion": ("las preguntas de implicación como el predictor más fuerte de éxito en ventas grandes",
                        "los capítulos sobre la secuencia SPIN"),
        "spin": ("la progresión situación, problema, implicación y necesidad-beneficio",
                 "la parte que desarrolla el modelo completo"),
        "cierre-grande": ("las técnicas de cierre agresivo mejoran la venta pequeña y empeoran la grande",
                          "el capítulo sobre cierre"),
        "objeciones-prevencion": ("las objeciones se previenen en la investigación, no se manejan en el cierre",
                                  "el capítulo sobre manejo de objeciones"),
        "necesidad-explicita": ("la diferencia entre necesidad implícita y explícita y su valor predictivo",
                                "los capítulos sobre desarrollo de necesidades"),
        "avance": ("el avance frente a la continuación: qué distingue una reunión que progresa",
                   "el capítulo sobre los cuatro resultados de una visita"),
    },
    "dixon-challenger": {
        "perfiles": ("los cinco perfiles comerciales y el desempeño superior del retador en venta compleja",
                     "los capítulos sobre los perfiles de vendedor"),
        "ensenar": ("enseñar para diferenciar: el insight comercial que reencuadra el problema del cliente",
                    "los capítulos sobre enseñanza comercial"),
        "adaptar": ("adaptar el mensaje a la economía y al lenguaje del interlocutor",
                    "el capítulo sobre adaptación"),
        "control": ("tomar el control de la conversación de precio y de proceso sin ceder ni imponer",
                    "el capítulo sobre control constructivo"),
        "insight-comercial": ("el insight que lleva de forma natural a la ventaja propia y no a una recomendación genérica",
                              "los capítulos sobre construcción del insight"),
    },
    "dixon-customer": {
        "mobilizer": ("los perfiles del comité de compra y los tres que sí movilizan el cambio",
                      "los capítulos sobre el cliente retador"),
        "consenso": ("el consenso interno como principal obstáculo, por encima de la persuasión individual",
                     "los capítulos iniciales sobre el problema del consenso"),
        "habilitar": ("habilitar al mobilizer con material que defienda el proyecto en ausencia del vendedor",
                      "los capítulos sobre comercialización colectiva"),
        "disrupcion-interna": ("la venta que reconfigura la conversación interna del cliente antes que la externa",
                               "los capítulos sobre movilización del consenso"),
    },
    "keenan": {
        "brecha": ("la brecha entre estado actual y estado futuro como objeto real de la venta",
                   "los capítulos sobre el modelo de la brecha"),
        "diagnostico": ("el diagnóstico riguroso antes de cualquier propuesta de solución",
                        "los capítulos sobre el rol del diagnóstico"),
        "impacto": ("el impacto técnico y de negocio del problema, cuantificado por el cliente",
                    "los capítulos sobre impacto"),
        "estado-actual": ("la reconstrucción factual del estado actual antes de proyectar el futuro",
                          "los capítulos sobre descubrimiento del estado actual"),
    },
    "blount": {
        "disciplina": ("la disciplina de actividad sostenida frente al ciclo de abundancia y sequía",
                       "los capítulos sobre la ley del pipeline"),
        "retardo": ("la ley del retardo universal: el pipeline responde con desfase a la actividad de hoy",
                    "el capítulo sobre el desfase del pipeline"),
        "rechazo": ("la gestión emocional del rechazo como habilidad entrenable",
                    "los capítulos sobre resiliencia en prospección"),
        "cadencia": ("la cadencia multicanal equilibrada en lugar de un solo canal saturado",
                     "los capítulos sobre metodología de prospección"),
        "bloques": ("los bloques de tiempo protegidos como mecanismo, no como intención",
                    "los capítulos sobre gestión del tiempo"),
    },
    "weinberg-sales": {
        "lista-objetivo": ("la lista objetivo acotada y trabajada, en lugar del universo completo",
                           "los capítulos sobre selección de cuentas objetivo"),
        "relato-comercial": ("el relato comercial construido desde los problemas del cliente, no desde la empresa",
                             "los capítulos sobre la historia de ventas"),
        "proceso-nueva-venta": ("el proceso de nueva venta separado de la gestión de cuentas existentes",
                                "los capítulos sobre el marco de nueva venta"),
    },
    "ross": {
        "especializacion": ("la especialización de roles comerciales: prospección, cierre y gestión separados",
                            "los capítulos sobre especialización del equipo"),
        "pipeline-predecible": ("el pipeline predecible derivado de una relación medida entre actividad y resultado",
                                "los capítulos sobre generación predecible"),
        "cold-calling-2": ("la prospección por referencia interna en lugar de la llamada en frío clásica",
                           "los capítulos sobre el método de prospección"),
        "tipos-lead": ("la distinción entre semillas, redes y lanzas como orígenes de demanda",
                       "el capítulo sobre los tres tipos de lead"),
    },
    "miller-heiman": {
        "roles-compra": ("los roles de compra: usuario, técnico, económico y entrenador",
                         "los capítulos sobre influencias de compra"),
        "senal-alerta": ("las señales de alerta y las fortalezas como diagnóstico de posición en la cuenta",
                         "los capítulos sobre análisis de posición"),
        "resultado-ganar": ("la distinción entre el resultado del negocio y la ganancia personal de cada rol",
                            "los capítulos sobre resultados y ganancias"),
        "plan-cuenta": ("el plan de cuenta como documento vivo con posición, riesgos y siguiente acción",
                        "los capítulos sobre planificación estratégica de cuentas"),
    },
    "roberge": {
        "contratacion-datos": ("el perfil de contratación derivado del desempeño observado en la propia empresa",
                               "los capítulos sobre la fórmula de contratación"),
        "formacion": ("la formación estandarizada con certificación por componente",
                      "los capítulos sobre la fórmula de entrenamiento"),
        "metricas-coaching": ("el acompañamiento dirigido por una métrica diagnóstica por vendedor",
                              "los capítulos sobre la fórmula de gestión"),
        "demanda": ("la generación de demanda medida por conversión a oportunidad y no por volumen",
                    "los capítulos sobre la fórmula de generación de demanda"),
        "proceso-comprador": ("el proceso comercial construido sobre el proceso de compra del cliente",
                              "los capítulos sobre alineación con el comprador"),
    },
    "bertuzzi": {
        "modelo-sdr": ("los modelos de organización del desarrollo de ventas y cuándo conviene cada uno",
                       "los capítulos sobre estructura del equipo"),
        "metricas-sdr": ("las métricas de desarrollo de ventas y la que realmente predice el resultado",
                         "los capítulos sobre medición"),
        "especializacion-sdr": ("la separación entre respuesta a demanda entrante y prospección saliente",
                                "los capítulos sobre especialización"),
    },
    "vaynerchuk": {
        "aporte-antes": ("la secuencia de aporte de valor repetido antes de la petición comercial",
                         "la tesis central del libro"),
        "contexto-canal": ("el mensaje adaptado a la gramática nativa de cada plataforma",
                           "los capítulos por plataforma"),
    },

    # ================================================================ NEGOCIACIÓN
    "fisher-ury": {
        "intereses": ("negociar sobre intereses y no sobre posiciones",
                      "el capítulo sobre intereses frente a posiciones"),
        "batna": ("la mejor alternativa al acuerdo negociado como fuente real de poder",
                  "el capítulo sobre la alternativa al acuerdo"),
        "criterios-objetivos": ("los criterios objetivos e independientes de la voluntad de las partes",
                                "el capítulo sobre criterios objetivos"),
        "opciones": ("la generación de opciones de beneficio mutuo antes de evaluarlas",
                     "el capítulo sobre invención de opciones"),
        "personas-problema": ("separar a las personas del problema",
                              "el capítulo sobre personas y problema"),
    },
    "ury": {
        "no-reaccionar": ("subir al balcón: no reaccionar en el momento de mayor presión",
                          "el primer paso del método de superación"),
        "reencuadre": ("el reencuadre de un ataque como intento de resolver el problema",
                       "el paso sobre reencuadrar"),
        "puente-dorado": ("el puente dorado: facilitar el retroceso del otro sin humillación",
                          "el paso sobre construir un puente"),
        "poder-educar": ("usar el poder para educar sobre el costo del no acuerdo, no para vencer",
                         "el paso final del método"),
    },
    "voss": {
        "etiquetado": ("el etiquetado de emociones para desactivarlas y obtener información",
                       "los capítulos sobre etiquetado"),
        "preguntas-calibradas": ("las preguntas calibradas que trasladan el problema al otro lado",
                                 "el capítulo sobre preguntas calibradas"),
        "espejo": ("la técnica del espejo para sostener el turno y obtener elaboración",
                   "el capítulo sobre reflejo"),
        "no-como-inicio": ("el «no» como comienzo de la negociación y no como final",
                           "el capítulo sobre el valor del no"),
        "cisnes-negros": ("la información desconocida que cambia el marco completo de la negociación",
                          "el capítulo sobre cisnes negros"),
    },
    "malhotra-neg": {
        "preparacion": ("la preparación analítica con rango, alternativas y criterios antes de sentarse",
                        "los capítulos sobre preparación"),
        "zopa": ("la zona de posible acuerdo derivada de los valores de reserva de ambas partes",
                 "los capítulos sobre el marco analítico"),
        "crear-reclamar": ("la tensión entre crear valor y reclamarlo en la misma mesa",
                           "los capítulos sobre negociación integrativa"),
        "tacticas-dificiles": ("el manejo de tácticas duras nombrándolas en lugar de responderlas",
                               "los capítulos sobre negociadores difíciles"),
        "etica": ("los límites éticos y el costo reputacional del engaño en negociación",
                  "los capítulos sobre ética en la negociación"),
        "informacion": ("la investigación previa como sustituto del poder cuando no se tiene",
                        "los capítulos sobre negociar desde la debilidad"),
    },
    "shell": {
        "estilos": ("los estilos de negociación y el efecto de conocer el propio",
                    "los capítulos sobre estilo personal"),
        "legitimidad": ("los estándares de legitimidad que las partes aceptan como justos",
                        "los capítulos sobre autoridad y normas"),
        "autoridad": ("la autoridad real frente a la declarada en la mesa",
                      "los capítulos sobre poder y autoridad"),
        "cultura": ("las diferencias culturales en ritmo, formalidad y rol del contrato",
                    "los capítulos sobre negociación intercultural"),
    },

    # ================================================================ DIGITAL Y CONVERSIÓN
    "chaffey": {
        "planificacion": ("el marco de planificación digital: situación, objetivos, estrategia, táctica, acción y control",
                          "los capítulos sobre planificación de marketing digital"),
        "medios-propios": ("la distinción entre medios propios, ganados y pagados",
                           "el capítulo sobre canales digitales"),
        "modelo-canal": ("el modelo de contribución de canal a la conversión",
                         "los capítulos sobre estrategia de canales"),
        "gobierno-digital": ("el gobierno de la operación digital: capacidades, procesos y medición",
                             "los capítulos sobre transformación y capacidades"),
        "omnicanal": ("la integración de la experiencia entre canales digitales y físicos",
                      "los capítulos sobre multicanalidad"),
    },
    "kaushik": {
        "vanidad": ("la distinción entre métricas de vanidad y métricas accionables",
                    "los capítulos sobre selección de métricas"),
        "segmentacion": ("la segmentación como condición para que un promedio signifique algo",
                         "el capítulo sobre segmentación de datos"),
        "plan-medicion": ("el plan de medición que va de la decisión a la métrica y no al revés",
                          "los capítulos sobre estrategia de medición"),
        "10-90": ("la regla 10/90: invertir en el analista, no en la herramienta",
                  "el capítulo sobre la regla 10/90"),
        "multiplicidad": ("la multiplicidad: combinar clics, resultados, experiencia y competencia",
                          "los capítulos sobre analítica multicanal"),
        "so-what": ("la prueba del «¿y entonces qué?» aplicada tres veces a cada informe",
                    "los capítulos sobre informes accionables"),
    },
    "enge-seo": {
        "intencion": ("la intención de búsqueda como criterio de priorización por encima del volumen",
                      "los capítulos sobre investigación de palabras clave"),
        "arquitectura": ("la arquitectura del sitio y su efecto sobre rastreo e indexación",
                         "los capítulos sobre SEO técnico"),
        "autoridad": ("las señales de autoridad y su construcción legítima",
                      "los capítulos sobre enlaces y autoridad"),
        "canibalizacion": ("la canibalización entre páginas propias que compiten por la misma intención",
                           "los capítulos sobre estrategia de contenido"),
    },
    "geddes": {
        "estructura-cuenta": ("la estructura de cuenta por intención como condición del control presupuestario",
                              "los capítulos sobre organización de campañas"),
        "calidad": ("el nivel de calidad y su efecto sobre el costo por clic",
                    "los capítulos sobre nivel de calidad"),
        "coincidencia": ("los tipos de coincidencia y las exclusiones como control del gasto",
                         "los capítulos sobre palabras clave y concordancias"),
        "subasta": ("la mecánica de la subasta: no gana quien más paga sino quien combina oferta y relevancia",
                    "los capítulos sobre funcionamiento de la subasta"),
    },
    "eisenberg": {
        "escenarios": ("los escenarios de conversión construidos desde la intención del visitante",
                       "los capítulos sobre planificación de escenarios"),
        "hipotesis-cro": ("la hipótesis explícita antes del test y su relación con la persuasión",
                          "los capítulos sobre proceso de optimización"),
        "friccion-formulario": ("la fricción del formulario y su efecto medible sobre el abandono",
                                "los capítulos sobre puntos de conversión"),
    },
    "laja": {
        "investigacion-previa": ("la investigación previa al test: sin diagnóstico, el experimento es una apuesta",
                                 "el método de investigación de conversión"),
        "potencia": ("el cálculo de muestra y potencia antes de iniciar cualquier prueba",
                     "las guías sobre validez estadística"),
        "jerarquia-mensaje": ("la jerarquía del mensaje según las preguntas reales del visitante",
                              "las guías sobre estructura de páginas"),
        "falsos-positivos": ("la tasa de resultados que no se replican y sus causas",
                             "las guías sobre errores frecuentes en experimentación"),
    },
    "flint": {
        "migracion-clientes": ("el análisis de migración de clientes entre canales y categorías",
                               "los capítulos sobre comportamiento multicanal"),
        "valor-canal": ("la contribución real de cada canal descontando lo que habría ocurrido igual",
                        "los capítulos sobre análisis forense de canales"),
        "recompra": ("los patrones de recompra que distinguen un negocio de compra única de uno recurrente",
                     "los capítulos sobre ciclos de compra"),
    },

    # ================================================================ GROWTH Y PRODUCTO
    "ellis-brown": {
        "ciclo": ("el ciclo de crecimiento: analizar, idear, priorizar y probar, ejecutado con ritmo fijo",
                  "los capítulos sobre el proceso de experimentación"),
        "aha": ("el momento «ajá» identificado con datos y no supuesto",
                "los capítulos sobre el momento de valor"),
        "equipo-multifuncional": ("el equipo multifuncional con acceso a producto, datos y marketing",
                                  "los capítulos sobre formación del equipo"),
        "must-have": ("la prueba de imprescindibilidad antes de acelerar la adquisición",
                      "los capítulos sobre encaje producto-mercado"),
        "backlog": ("el backlog de experimentos con hipótesis y criterio previo",
                    "los capítulos sobre priorización de pruebas"),
    },
    "ries-lean": {
        "construir-medir": ("el ciclo construir-medir-aprender y la minimización del tiempo total del ciclo",
                            "la parte sobre el motor de crecimiento"),
        "mvp": ("el producto mínimo viable como experimento y no como versión reducida",
                "los capítulos sobre el MVP"),
        "aprendizaje-validado": ("el aprendizaje validado como unidad de progreso frente a los hitos de plan",
                                 "los capítulos sobre aprendizaje validado"),
        "pivote": ("el pivote como cambio estructurado de hipótesis, con tipos definidos",
                   "los capítulos sobre pivotar o perseverar"),
        "contabilidad-innovacion": ("la contabilidad de la innovación con métricas de cohorte en lugar de acumuladas",
                                    "los capítulos sobre contabilidad de la innovación"),
    },
    "weinberg-traction": {
        "bullseye": ("el método bullseye para elegir canal entre diecinueve opciones",
                     "los capítulos sobre el marco bullseye"),
        "canales": ("el catálogo de canales de tracción y el sesgo a repetir el que ya se conoce",
                    "los capítulos que recorren cada canal"),
        "50-50": ("la regla de dedicar la mitad del esfuerzo a producto y la mitad a tracción",
                  "los capítulos iniciales sobre la regla 50/50"),
    },
    "croll-yoskovitz": {
        "una-metrica": ("la métrica que importa ahora: una sola, según etapa y modelo de negocio",
                        "los capítulos sobre la métrica única"),
        "etapas": ("las cinco etapas —empatía, adherencia, viralidad, ingreso y escala— con su métrica propia",
                   "la parte sobre etapas del negocio"),
        "modelos": ("los seis modelos de negocio y las métricas que cambian entre ellos",
                    "la parte sobre modelos de negocio"),
        "linea-trazada": ("la línea trazada de antemano: qué valor haría considerar exitoso el experimento",
                          "los capítulos sobre definir el éxito"),
        "cohortes": ("el análisis de cohortes como corrección al promedio que esconde la mezcla",
                     "el capítulo sobre cohortes y segmentación"),
    },
    "bush-plg": {
        "autoservicio": ("las condiciones que hacen viable el autoservicio: valor perceptible sin asistencia",
                         "los capítulos sobre el modelo liderado por producto"),
        "moment-value": ("el momento de valor y su distancia respecto del registro",
                         "los capítulos sobre tiempo hasta el valor"),
        "modelo-gratuito": ("la elección entre prueba gratuita y plan libre según el producto",
                            "los capítulos sobre modelos de acceso"),
        "ocasion-upgrade": ("el gatillo de conversión construido alrededor del valor y no del tiempo",
                            "los capítulos sobre conversión a plan pagado"),
    },
    "cagan": {
        "riesgos": ("los cuatro riesgos de producto: valor, usabilidad, viabilidad y factibilidad",
                    "los capítulos sobre riesgos del descubrimiento"),
        "descubrimiento": ("el descubrimiento continuo separado de la entrega",
                           "la parte sobre descubrimiento de producto"),
        "resultado-output": ("la orientación a resultado en lugar de a entrega de funcionalidades",
                             "los capítulos sobre equipos de producto"),
        "roadmap": ("la crítica al roadmap de funcionalidades con fechas y su reemplazo por objetivos",
                    "los capítulos sobre roadmaps de producto"),
    },
    "kohavi": {
        "confianza": ("las condiciones que hacen confiable un experimento en línea",
                      "los capítulos sobre experimentos confiables"),
        "guardarrailes": ("las métricas guardarraíl que impiden ganar en lo local perdiendo en el sistema",
                          "los capítulos sobre métricas y guardarraíles"),
        "detencion-temprana": ("la detención temprana y el espionaje de resultados como fuente de falsos positivos",
                               "los capítulos sobre errores comunes"),
        "efecto-minimo": ("el efecto mínimo relevante como base del cálculo de muestra",
                          "los capítulos sobre potencia y tamaño de muestra"),
        "twyman": ("la ley de Twyman: un resultado sorprendentemente bueno suele ser un error de medición",
                   "los capítulos sobre interpretación de resultados"),
        "metricas-sustitutas": ("los riesgos de optimizar una métrica sustituta en lugar del resultado",
                                "los capítulos sobre selección de métricas"),
    },
    "hulick": {
        "primer-exito": ("el onboarding diseñado hacia el primer éxito y no hacia el recorrido del producto",
                         "los capítulos sobre objetivos del onboarding"),
        "carga-cognitiva": ("la reducción de carga cognitiva en los primeros minutos",
                            "los capítulos sobre diseño de la primera experiencia"),
        "vacio-inicial": ("el estado vacío como oportunidad de guiar y no como pantalla en blanco",
                          "los capítulos sobre estados vacíos"),
    },

    # ================================================================ RETENCIÓN
    "mehta": {
        "resultado-cliente": ("el resultado deseado del cliente más la experiencia apropiada como definición de éxito",
                              "los capítulos sobre la definición de customer success"),
        "leyes": ("las leyes del éxito de cliente, entre ellas que vender al cliente equivocado destruye la retención",
                  "la parte que enuncia las diez leyes"),
        "salud": ("el puntaje de salud construido con uso, resultado y relación, validado contra bajas",
                  "los capítulos sobre health score"),
        "segmentacion-cs": ("los modelos de cobertura según valor y complejidad de la cuenta",
                            "los capítulos sobre modelos de atención"),
        "expansion": ("la expansión condicionada al resultado inicial acreditado",
                      "los capítulos sobre crecimiento en la base instalada"),
    },
    "reichheld": {
        "nps-uso": ("los usos correctos e incorrectos del indicador de recomendación",
                    "los capítulos sobre medición de lealtad"),
        "cliente-ganado": ("la economía del cliente ganado: crecimiento por recomendación frente a crecimiento comprado",
                           "los capítulos sobre crecimiento ganado"),
        "cierre-circuito": ("el cierre del circuito con quien respondió como parte del sistema",
                            "los capítulos sobre el proceso de retroalimentación"),
        "proposito": ("el propósito de enriquecer la vida del cliente como criterio de decisión comercial",
                      "los capítulos iniciales sobre propósito"),
    },
    "fader": {
        "heterogeneidad": ("la heterogeneidad del valor del cliente: no todos valen lo mismo ni deben tratarse igual",
                           "los capítulos sobre centricidad en el cliente"),
        "centricidad": ("la centricidad como asignación desigual de recursos según valor esperado",
                        "los capítulos que definen la centricidad"),
        "rfm": ("recencia, frecuencia y valor como base de segmentación conductual",
                "los capítulos sobre segmentación por comportamiento"),
        "producto-vs-cliente": ("la diferencia entre una empresa centrada en producto y una centrada en cliente",
                                "los capítulos comparativos"),
    },
    "fader-ltv": {
        "ltv-modelo": ("el valor de vida como proyección con supuestos declarados y no como cifra única",
                       "los capítulos sobre cálculo del valor de vida"),
        "cohortes-valor": ("las cohortes como base del cálculo, frente al promedio agregado",
                           "los capítulos sobre análisis por cohorte"),
        "inversion-diferencial": ("la inversión diferenciada por valor esperado del cliente",
                                  "los capítulos sobre decisiones de inversión"),
    },
    "dixon-effort": {
        "esfuerzo": ("la reducción del esfuerzo del cliente predice lealtad mejor que el deleite",
                     "los capítulos que presentan la evidencia"),
        "resolucion-siguiente": ("la resolución del siguiente problema previsible en el mismo contacto",
                                 "los capítulos sobre resolución anticipada"),
        "canal-preferido": ("el traslado forzado de canal como fuente principal de esfuerzo percibido",
                            "los capítulos sobre experiencia de canal"),
        "lenguaje": ("el lenguaje del agente como palanca sobre la percepción de esfuerzo",
                     "los capítulos sobre ingeniería del lenguaje"),
    },

    # ================================================================ OPERACIONES Y DIRECCIÓN
    "diorio": {
        "sistema-ingresos": ("el ingreso como resultado de un sistema integrado y no de tres áreas separadas",
                             "los capítulos introductorios sobre revenue operations"),
        "modelo-datos": ("el modelo de datos común como condición para que las áreas discutan sobre lo mismo",
                         "los capítulos sobre infraestructura de datos comercial"),
        "definiciones": ("la definición única por indicador como acuerdo previo a cualquier tablero",
                         "los capítulos sobre gobierno de métricas"),
        "friccion": ("la fricción en los traspasos entre áreas como pérdida medible de ingreso",
                     "los capítulos sobre procesos de ingreso"),
    },
    "doerr": {
        "okr": ("los objetivos con resultados clave medibles y su separación de la compensación",
                "los capítulos que definen el sistema OKR"),
        "foco": ("el foco: pocos objetivos, con lo descartado explícito",
                 "los capítulos sobre comprometerse con prioridades"),
        "transparencia": ("la transparencia de objetivos como mecanismo de alineamiento",
                          "los capítulos sobre alineación y conexión"),
        "seguimiento": ("el seguimiento con revisión y recalibración durante el ciclo",
                        "los capítulos sobre seguimiento y responsabilidad"),
    },
    "grove": {
        "output-gerencial": ("el output del gerente es el de su organización más el de las unidades que influye",
                             "los capítulos sobre el trabajo del gerente"),
        "indicadores-adelantados": ("los indicadores adelantados y pareados que permiten corregir a tiempo",
                                    "los capítulos sobre medición en la producción"),
        "reuniones": ("las reuniones como herramienta de producción con propósito y formato definidos",
                      "los capítulos sobre reuniones"),
        "delegacion": ("la delegación con nivel de supervisión ajustado a la madurez de la tarea",
                       "los capítulos sobre madurez relevante a la tarea"),
        "apalancamiento": ("el apalancamiento gerencial: qué actividades multiplican el output",
                           "los capítulos sobre apalancamiento"),
    },
    "kaplan-norton": {
        "mapa-estrategico": ("el mapa estratégico que conecta causalmente objetivos entre perspectivas",
                             "los capítulos sobre relaciones causa-efecto"),
        "cuatro-perspectivas": ("las cuatro perspectivas: financiera, cliente, procesos y aprendizaje",
                                "los capítulos que presentan el cuadro de mando"),
        "indicadores-causales": ("los inductores de actuación frente a los indicadores de resultado",
                                 "los capítulos sobre tipos de indicador"),
        "traduccion": ("la traducción de la estrategia en indicadores que la organización puede ejecutar",
                       "los capítulos sobre implantación"),
    },
    "zoltners": {
        "cuotas": ("el diseño de cuotas alcanzables derivadas del potencial y no del deseo",
                   "los capítulos sobre diseño de cuotas"),
        "territorios": ("el diseño de territorios y la equidad de oportunidad entre vendedores",
                        "los capítulos sobre alineación de territorios"),
        "incentivos": ("los efectos no deseados que produce cada estructura de incentivo",
                       "los capítulos sobre diseño de planes de compensación"),
        "aceleradores": ("los aceleradores y topes y su efecto sobre el comportamiento al final del periodo",
                         "los capítulos sobre mecánica del plan"),
    },
    "sinek": {
        "porque": ("el círculo dorado: comunicar desde el porqué antes que desde el qué",
                   "los capítulos que presentan el círculo dorado"),
        "coherencia": ("la coherencia entre el porqué declarado y las decisiones observables",
                       "los capítulos sobre claridad, disciplina y consistencia"),
    },
    "collins": {
        "erizo": ("el concepto del erizo: la intersección entre pasión, capacidad y motor económico",
                  "el capítulo sobre el concepto del erizo"),
        "personas-primero": ("primero quién y después qué: las personas correctas antes que la dirección",
                             "el capítulo sobre primero quién"),
        "disciplina": ("la cultura de disciplina que hace innecesaria la jerarquía excesiva",
                       "el capítulo sobre cultura de disciplina"),
        "hechos-brutales": ("enfrentar los hechos brutales sin perder la fe en el resultado",
                            "el capítulo sobre la paradoja de Stockdale"),
    },
    "lencioni": {
        "confianza": ("la confianza basada en vulnerabilidad como base de las demás disciplinas",
                      "la base del modelo de las cinco disfunciones"),
        "conflicto": ("el conflicto productivo sobre ideas frente a la armonía artificial",
                      "el nivel de conflicto del modelo"),
        "accountability": ("la responsabilidad entre pares como mecanismo más fuerte que la supervisión",
                           "el nivel de accountability del modelo"),
        "resultados": ("la atención al resultado colectivo por encima del estatus individual",
                       "la cúspide del modelo"),
    },

    # ================================================================ DATOS, IA Y ÉTICA
    "provost": {
        "formulacion": ("la formulación del problema de negocio como problema de datos antes de elegir técnica",
                        "los capítulos iniciales sobre pensamiento analítico"),
        "valor-esperado": ("el marco de valor esperado que combina probabilidad y consecuencia económica",
                           "el capítulo sobre valor esperado"),
        "evaluacion": ("la evaluación contra una línea base y no contra la nada",
                       "los capítulos sobre evaluación de modelos"),
        "asociacion-causalidad": ("la distinción entre correlación observada y causalidad y qué exige cada una",
                                  "los capítulos sobre inferencia y sesgo"),
        "sobreajuste": ("el sobreajuste y la validación fuera de muestra",
                        "los capítulos sobre sobreajuste"),
        "fuga-datos": ("la fuga de información: un modelo que predice demasiado bien suele estar mal construido",
                       "los capítulos sobre problemas de datos"),
    },
    "wheeler-dv": {
        "variacion-comun": ("la distinción entre variación común y variación especial antes de reaccionar",
                            "los capítulos que introducen la distinción"),
        "graficos-control": ("los gráficos de comportamiento del proceso como filtro entre señal y ruido",
                             "los capítulos sobre gráficos de control"),
        "comparar-dos-puntos": ("el error de comparar dos puntos consecutivos y llamarlo tendencia",
                                "los capítulos sobre interpretación de series"),
    },
    "hubbard": {
        "valor-informacion": ("el valor esperado de la información: cuánto vale reducir la incertidumbre antes de medir",
                              "los capítulos sobre el valor de la medición"),
        "medicion-definicion": ("medir es reducir incertidumbre, no eliminarla",
                                "los capítulos que redefinen la medición"),
        "calibracion": ("la calibración de estimaciones subjetivas como habilidad entrenable",
                        "los capítulos sobre estimación calibrada"),
        "dilema-medicion": ("lo que parece inmedible suele estar mal definido, no ser inmedible",
                            "los capítulos sobre el problema de la medición"),
    },
    "oneil": {
        "armas": ("las tres condiciones que convierten un modelo en dañino: opacidad, escala y daño",
                  "los capítulos introductorios que definen el concepto"),
        "retroalimentacion": ("los bucles de retroalimentación que confirman el sesgo del modelo",
                              "los capítulos sobre bucles perniciosos"),
        "proxy": ("las variables sustitutas que codifican prejuicio sin nombrarlo",
                  "los capítulos sobre selección de variables"),
        "auditoria": ("la exigencia de auditabilidad en modelos que afectan a personas",
                      "el capítulo final sobre desarme"),
    },
    "russell-norvig": {
        "agente-racional": ("el agente racional definido por su medida de desempeño, entorno, actuadores y sensores",
                            "los capítulos sobre agentes inteligentes"),
        "medida-desempeno": ("la medida de desempeño como definición previa a cualquier evaluación",
                             "el capítulo sobre racionalidad"),
        "entorno": ("la caracterización del entorno: observable, determinista, episódico y sus consecuencias",
                    "el capítulo sobre propiedades del entorno"),
    },
    "ng-mlyearning": {
        "diagnostico": ("el diagnóstico de errores antes de elegir la siguiente mejora",
                        "los capítulos sobre análisis de error"),
        "conjunto-evaluacion": ("el conjunto de evaluación que representa la distribución real de uso",
                                "los capítulos sobre conjuntos de desarrollo y prueba"),
        "metrica-unica": ("una métrica de evaluación única para poder comparar alternativas",
                          "los capítulos sobre métricas de evaluación"),
    },
    "nist-airmf": {
        "funciones": ("las cuatro funciones: mapear, medir, gestionar y gobernar el riesgo de IA",
                      "el núcleo del marco"),
        "gobernar": ("la función de gobierno como condición transversal a las demás",
                     "la sección sobre la función gobernar"),
        "caracteristicas": ("las características de un sistema de IA confiable, incluidas trazabilidad y responsabilidad",
                            "la sección sobre confiabilidad"),
        "contexto": ("el riesgo evaluado en el contexto de uso y no en abstracto",
                     "la sección sobre mapeo del contexto"),
    },
    "iso-31000": {
        "proceso": ("el proceso de gestión del riesgo: identificar, analizar, evaluar y tratar",
                    "la cláusula sobre el proceso"),
        "principios": ("los principios: integrado, estructurado, adaptado y basado en la mejor información disponible",
                       "la cláusula sobre principios"),
        "riesgo-residual": ("el riesgo residual aceptado de forma explícita y documentada",
                            "la cláusula sobre tratamiento del riesgo"),
    },

    # ================================================================ PEDAGOGÍA
    "ambrose": {
        "conocimiento-previo": ("el conocimiento previo como facilitador o como obstáculo del aprendizaje nuevo",
                                "el principio sobre conocimiento previo"),
        "practica-feedback": ("la práctica dirigida a un objetivo con retroalimentación oportuna",
                              "el principio sobre práctica y retroalimentación"),
        "organizacion": ("la organización del conocimiento y su efecto sobre la recuperación",
                         "el principio sobre organización del conocimiento"),
        "motivacion": ("el valor percibido y la expectativa de éxito como determinantes de la motivación",
                       "el principio sobre motivación"),
    },
    "brown-mis": {
        "recuperacion": ("la práctica de recuperación supera a la relectura como método de estudio",
                         "los capítulos sobre recuperación"),
        "espaciado": ("el espaciado y el intercalado frente a la práctica masiva",
                      "los capítulos sobre práctica espaciada"),
        "dificultad-deseable": ("las dificultades deseables que hacen el aprendizaje más lento y más duradero",
                                "los capítulos sobre dificultades deseables"),
        "ilusion-fluidez": ("la ilusión de fluidez: la facilidad de lectura se confunde con dominio",
                            "los capítulos sobre ilusiones del conocimiento"),
    },
    "wiggins": {
        "diseno-inverso": ("el diseño inverso: primero el desempeño observable, después el contenido",
                           "los capítulos sobre las tres etapas del diseño"),
        "comprension": ("las seis facetas de la comprensión, incluida la capacidad de explicar y aplicar",
                        "los capítulos sobre facetas de la comprensión"),
        "evidencia": ("la evidencia aceptable de aprendizaje definida antes de planificar la enseñanza",
                      "la segunda etapa del diseño"),
    },
    "ericsson": {
        "practica-deliberada": ("la práctica deliberada con objetivo específico, retroalimentación inmediata y salida de la zona de confort",
                                "los capítulos que definen la práctica deliberada"),
        "representaciones": ("las representaciones mentales que distinguen al experto del principiante",
                             "los capítulos sobre representaciones mentales"),
        "maestro": ("el papel del maestro o entrenador que provee criterio externo",
                    "los capítulos sobre el rol del entrenador"),
    },
    "ellet": {
        "tipos-caso": ("los cuatro tipos de caso: problema, decisión, evaluación y regla",
                       "los capítulos sobre tipos de situación"),
        "analisis-decision": ("el análisis de un caso de decisión: alternativas, criterios y evidencia",
                              "el capítulo sobre casos de decisión"),
        "argumento": ("la construcción del argumento con posición, razones y evidencia",
                      "los capítulos sobre escritura y discusión de casos"),
        "evidencia-caso": ("la distinción entre evidencia del caso e inferencia del lector",
                           "los capítulos sobre análisis de situaciones"),
    },
}


def aporte(clave_obra, identificador):
    """Devuelve (idea, dónde buscarla) del aporte anclado."""
    return APORTES[clave_obra][identificador]


def identificadores(clave_obra):
    return sorted(APORTES.get(clave_obra, {}))


def total_aportes():
    return sum(len(v) for v in APORTES.values())
