# -*- coding: utf-8 -*-
"""Definición de las 24 partes del programa.

Cada parte declara: nivel, resultado esperado, pregunta rectora, artefacto de
portafolio, competencias, roles a los que habilita, bibliografía rectora y el
tramo del caso persistente que se trabaja.

El caso persistente es **Ruta Andina SpA** (ver `EMPRESA`): permite recorrer B2B
SaaS, e-commerce, marketplace y venta al sector público sin cambiar de contexto,
de modo que las decisiones de una parte condicionen las siguientes.
"""

EMPRESA = {
    "nombre": "Ruta Andina SpA",
    "descripcion": (
        "Empresa chilena que vende una plataforma de agendamiento, pagos y CRM ligero "
        "para pymes de servicios (peluquerías, talleres, centros médicos pequeños, "
        "estudios contables). Tiene tres líneas de ingreso: suscripción SaaS "
        "(CLP 39.000 a CLP 199.000 mensuales por local), venta de hardware "
        "complementario por e-commerce y marketplace, y contratos anuales con "
        "municipios y corporaciones para digitalizar atención de público."
    ),
    "estado_inicial": (
        "18 meses de operación, 240 cuentas activas, ARR aproximado de CLP 610 millones, "
        "churn mensual de 3,4 %, equipo comercial de 6 personas, CAC mixto de CLP 310.000 "
        "y un CRM con datos incompletos. El directorio pide duplicar ingresos en 18 meses "
        "sin duplicar el gasto comercial."
    ),
    "restricciones": (
        "Presupuesto de marketing y ventas acotado, un solo analista de datos compartido, "
        "obligación de cumplir la Ley 19.496 del consumidor y de prepararse para la Ley "
        "21.719 de datos personales, y un competidor regional con más capital."
    ),
}

PARTES = [
    {
        "num": "01",
        "slug": "part-01-marketing-y-ventas-fundamentos-del-sistema-comercial",
        "titulo": "Marketing y ventas: fundamentos del sistema comercial",
        "nivel": "Fundamentos",
        "resultado": "explicar el motor de ingresos como un sistema y no como una suma de tácticas",
        "pregunta": "¿De qué depende realmente que esta empresa gane un cliente rentable y lo conserve?",
        "artefacto": "mapa del sistema comercial con supuestos, métricas y puntos de fuga",
        "competencias": ["pensamiento sistémico comercial", "definición operacional de métricas", "ética comercial"],
        "roles": ["Analista comercial", "Marketing generalista", "Founder"],
        "libros": ["kotler", "drucker", "levitt", "sharp", "godin", "diorio"],
        "caso": "El directorio de Ruta Andina cree que el problema es «falta de marketing». Los datos muestran conversión sana en demo y churn alto a los 90 días.",
        "riesgo": "Confundir actividad con resultado y comprometer presupuesto antes de tener un diagnóstico.",
    },
    {
        "num": "02",
        "slug": "part-02-cliente-y-comportamiento-del-consumidor",
        "titulo": "Cliente y comportamiento del consumidor",
        "nivel": "Fundamentos",
        "resultado": "construir un expediente de cliente accionable basado en evidencia y no en estereotipos",
        "pregunta": "¿Quién decide, quién usa, quién paga y qué progreso intenta lograr cada uno?",
        "artefacto": "expediente de cliente con ICP, unidad de decisión, journey y fricciones priorizadas",
        "competencias": ["investigación de cliente", "modelado de decisión de compra", "análisis de fricción"],
        "roles": ["Marketing manager", "Product marketing", "Ejecutivo comercial"],
        "libros": ["christensen", "ulwick", "solomon", "kahneman", "cialdini", "fitzpatrick"],
        "caso": "El equipo de Ruta Andina describe a su cliente como «pyme chilena». Con esa definición ninguna campaña ni ningún guion de venta puede afinarse.",
        "riesgo": "Construir personas ficticias sin datos y usarlas para justificar decisiones caras.",
    },
    {
        "num": "03",
        "slug": "part-03-investigacion-de-mercados-e-inteligencia-competitiva",
        "titulo": "Investigación de mercados e inteligencia competitiva",
        "nivel": "Fundamentos",
        "resultado": "producir investigación que cambie una decisión y resista una auditoría metodológica",
        "pregunta": "¿Qué evidencia mínima necesito para decidir, y qué sesgo podría estar produciéndola?",
        "artefacto": "informe de oportunidad de mercado con método, muestra, límites y decisión recomendada",
        "competencias": ["diseño de investigación", "muestreo y control de sesgos", "inteligencia competitiva"],
        "roles": ["Market researcher", "Product marketing", "Consultor comercial"],
        "libros": ["malhotra", "fitzpatrick", "portigal", "blank", "hubbard", "porter"],
        "caso": "Ruta Andina debe decidir si abre un vertical de centros médicos o profundiza en talleres mecánicos. Hay opiniones fuertes y cero datos comparables.",
        "riesgo": "Investigar para confirmar una decisión ya tomada y presentar el resultado como hallazgo.",
    },
    {
        "num": "04",
        "slug": "part-04-segmentacion-targeting-y-posicionamiento",
        "titulo": "Segmentación, targeting y posicionamiento",
        "nivel": "Fundamentos",
        "resultado": "elegir a quién servir y ocupar un lugar defendible en la mente del cliente",
        "pregunta": "¿Qué segmento puedo servir mejor que nadie y con qué diferencia comprobable?",
        "artefacto": "arquitectura STP con criterios de atractivo, accesibilidad y declaración de posicionamiento probada",
        "competencias": ["segmentación operativa", "priorización de segmentos", "posicionamiento comprobable"],
        "roles": ["Marketing manager", "Product marketing", "Head of Growth"],
        "libros": ["kotler", "ries-trout", "moore", "sharp", "porter-hbr", "rumelt"],
        "caso": "Ruta Andina tiene 240 cuentas repartidas en nueve rubros. El 70 % del margen viene de dos rubros que nadie priorizó de forma explícita.",
        "riesgo": "Segmentar con variables decorativas que no cambian oferta, canal ni mensaje.",
    },
    {
        "num": "05",
        "slug": "part-05-producto-oferta-y-propuesta-de-valor",
        "titulo": "Producto, oferta y propuesta de valor",
        "nivel": "Oferta comercial",
        "resultado": "convertir una capacidad técnica en una oferta que alguien quiera comprar hoy",
        "pregunta": "¿Qué compra realmente el cliente y por qué elegiría esta oferta frente a no hacer nada?",
        "artefacto": "oferta lista para vender con propuesta de valor, alcance, garantía y prueba de concepto",
        "competencias": ["diseño de oferta", "validación de propuesta de valor", "gestión de portafolio"],
        "roles": ["Product marketing", "Product manager", "Founder"],
        "libros": ["osterwalder-vpd", "christensen", "cagan", "ries-lean", "moore", "ramanujam"],
        "caso": "El plan de Ruta Andina se vende como «software de agendamiento». Los clientes que renuevan hablan de reducir inasistencias y cobrar más rápido.",
        "riesgo": "Prometer resultados que la operación no puede sostener y generar churn temprano.",
    },
    {
        "num": "06",
        "slug": "part-06-marca-branding-y-comunicacion-estrategica",
        "titulo": "Marca, branding y comunicación estratégica",
        "nivel": "Oferta comercial",
        "resultado": "construir activos de marca que reduzcan el costo de adquisición futuro",
        "pregunta": "¿Qué debe recordar el mercado sobre nosotros cuando aparece la necesidad?",
        "artefacto": "brand book mínimo viable con activos distintivos, promesa y sistema de medición",
        "competencias": ["identidad de marca", "coherencia omnicanal", "medición de marca"],
        "roles": ["Brand manager", "Marketing manager", "Comunicaciones"],
        "libros": ["aaker", "keller-brand", "sharp2", "wheeler", "heath", "binet-field"],
        "caso": "Ruta Andina cambió de logo dos veces en 18 meses y su nombre no aparece en la conversación espontánea del rubro.",
        "riesgo": "Confundir gusto estético del equipo con construcción de memoria en el mercado.",
    },
    {
        "num": "07",
        "slug": "part-07-pricing-y-monetizacion",
        "titulo": "Pricing y monetización",
        "nivel": "Oferta comercial",
        "resultado": "diseñar una arquitectura de precios que capture valor sin destruir demanda ni confianza",
        "pregunta": "¿Cuánto vale esto para quién, y qué estructura de cobro alinea precio con valor entregado?",
        "artefacto": "arquitectura de monetización con métrica de cobro, planes, price fences y política de descuentos",
        "competencias": ["pricing basado en valor", "análisis de disposición a pagar", "unit economics"],
        "roles": ["Pricing manager", "Product marketing", "CFO comercial", "Founder"],
        "libros": ["nagle", "simon", "ramanujam", "smith-pricing", "ariely", "croll-yoskovitz"],
        "caso": "Ruta Andina cobra por local y sus mejores clientes tienen varios locales pequeños. Los descuentos por cierre de mes ya se volvieron una expectativa.",
        "riesgo": "Erosionar precio con descuentos tácticos y perder capacidad de subir precios después.",
    },
    {
        "num": "08",
        "slug": "part-08-fundamentos-profesionales-de-ventas",
        "titulo": "Fundamentos profesionales de ventas",
        "nivel": "Venta",
        "resultado": "ejecutar un proceso comercial reproducible que no dependa del talento individual",
        "pregunta": "¿Qué debe ocurrir en cada etapa para que la siguiente sea probable y no accidental?",
        "artefacto": "playbook comercial con etapas, criterios de salida, guiones y materiales",
        "competencias": ["proceso comercial", "discovery estructurado", "manejo de objeciones"],
        "roles": ["Ejecutivo comercial", "SDR", "Jefe de ventas"],
        "libros": ["weinberg-sales", "rackham", "blount", "keenan", "roberge", "cialdini"],
        "caso": "En Ruta Andina dos vendedores cierran el 70 % del negocio y nadie sabe explicar qué hacen distinto. Cuando uno sale de vacaciones, el pipeline se detiene.",
        "riesgo": "Presionar por cierre sin diagnóstico y vender a clientes que no pueden obtener valor.",
    },
    {
        "num": "09",
        "slug": "part-09-venta-consultiva-y-b2b-compleja",
        "titulo": "Venta consultiva y B2B compleja",
        "nivel": "Venta",
        "resultado": "dirigir negocios con múltiples decisores, riesgo alto y ciclos largos",
        "pregunta": "¿Quién decide, quién bloquea, qué evidencia necesita cada uno y cuál es el costo de no decidir?",
        "artefacto": "deal review completo con mapa de cuenta, criterios de decisión y plan mutuo",
        "competencias": ["diagnóstico consultivo", "mapeo de comité de compra", "calificación rigurosa"],
        "roles": ["Account executive", "Key account manager", "Consultor de negocio"],
        "libros": ["rackham", "dixon-challenger", "dixon-customer", "miller-heiman", "keenan", "moore"],
        "caso": "Ruta Andina lleva cinco meses en una oportunidad con una cadena de 14 locales. El contacto entusiasta no tiene presupuesto y el gerente de finanzas nunca apareció.",
        "riesgo": "Confundir entusiasmo de un contacto con avance real y sostener un forecast falso.",
    },
    {
        "num": "10",
        "slug": "part-10-negociacion-comercial",
        "titulo": "Negociación comercial",
        "nivel": "Venta",
        "resultado": "negociar acuerdos sostenibles protegiendo precio, alcance y relación",
        "pregunta": "¿Qué intereses hay detrás de las posiciones y cuál es mi alternativa real si no hay acuerdo?",
        "artefacto": "carpeta de negociación con BATNA, ZOPA, concesiones planificadas y acuerdo documentado",
        "competencias": ["preparación de negociación", "creación y reclamo de valor", "documentación de acuerdos"],
        "roles": ["Account executive", "Jefe de ventas", "Compras", "Founder"],
        "libros": ["fisher-ury", "malhotra-neg", "voss", "ury", "shell", "nagle"],
        "caso": "El área de compras de la cadena exige 30 % de descuento, pago a 90 días y una cláusula de exclusividad. El vendedor ya adelantó que «hay espacio».",
        "riesgo": "Ceder margen y condiciones bajo presión de cierre de trimestre y crear precedente.",
    },
    {
        "num": "11",
        "slug": "part-11-prospeccion-y-generacion-de-demanda",
        "titulo": "Prospección y generación de demanda",
        "nivel": "Venta",
        "resultado": "construir un sistema de originación de oportunidades repetible y legítimo",
        "pregunta": "¿De dónde vendrá la próxima oportunidad calificada y a qué costo por unidad?",
        "artefacto": "sistema de prospección con listas, secuencias multicanal, mensajes y métricas por etapa",
        "competencias": ["construcción ética de listas", "cadencia multicanal", "calificación temprana"],
        "roles": ["SDR", "BDR", "Growth marketer", "Founder"],
        "libros": ["blount", "ross", "bertuzzi", "weinberg-traction", "godin", "handley"],
        "caso": "Ruta Andina compró una base de 12.000 contactos. La tasa de respuesta es 0,4 %, hay reclamos por spam y el dominio de correo empezó a caer en reputación.",
        "riesgo": "Infringir normas de datos personales y consumo, y quemar el activo reputacional del dominio.",
    },
    {
        "num": "12",
        "slug": "part-12-marketing-digital-y-adquisicion",
        "titulo": "Marketing digital y adquisición",
        "nivel": "Adquisición",
        "resultado": "operar un sistema digital de adquisición medible de punta a punta",
        "pregunta": "¿Qué activo digital genera demanda propia y qué parte del resultado es alquilada?",
        "artefacto": "plan de adquisición digital con arquitectura de sitio, canales, medición y auditoría inicial",
        "competencias": ["estrategia digital", "conversión web", "analítica y atribución básica"],
        "roles": ["Digital marketing manager", "Growth marketer", "Especialista SEO/SEM"],
        "libros": ["chaffey", "enge-seo", "kaushik", "krug", "eisenberg", "laja"],
        "caso": "El sitio de Ruta Andina recibe 9.000 visitas mensuales y genera 21 leads. Nadie sabe qué páginas producen demanda ni cuáles solo consumen presupuesto.",
        "riesgo": "Optimizar métricas de vanidad y desatender consentimiento, cookies y datos personales.",
    },
    {
        "num": "13",
        "slug": "part-13-contenido-copywriting-y-comunicacion-persuasiva",
        "titulo": "Contenido, copywriting y comunicación persuasiva",
        "nivel": "Adquisición",
        "resultado": "producir mensajes que informen, muevan a la acción y resistan el escrutinio",
        "pregunta": "¿Qué tiene que entender, creer y sentir esta persona para dar el siguiente paso?",
        "artefacto": "sistema editorial con pilares, calendario, guía de estilo y piezas probadas",
        "competencias": ["estrategia de contenidos", "copywriting comercial", "testing de mensajes"],
        "roles": ["Content manager", "Copywriter", "Product marketing"],
        "libros": ["handley", "sugarman", "heath", "ogilvy", "pulizzi", "cialdini"],
        "caso": "El blog de Ruta Andina publica dos artículos semanales sobre «tendencias digitales» y ninguno responde las preguntas que aparecen en las llamadas de venta.",
        "riesgo": "Publicar afirmaciones no verificables o promesas comerciales que infrinjan la ley del consumidor.",
    },
    {
        "num": "14",
        "slug": "part-14-publicidad-y-performance-marketing",
        "titulo": "Publicidad y performance marketing",
        "nivel": "Adquisición",
        "resultado": "invertir en medios pagados con control de costo, calidad y riesgo",
        "pregunta": "¿Qué unidad de resultado estoy comprando y a qué costo marginal deja de tener sentido?",
        "artefacto": "plan de performance con estructura de campañas, presupuestos, medición y salvaguardas",
        "competencias": ["gestión de subastas", "economía de campañas", "medición y brand safety"],
        "roles": ["Performance marketer", "Media buyer", "Growth marketer"],
        "libros": ["geddes", "kaushik", "binet-field", "ogilvy", "kohavi", "chaffey"],
        "caso": "Ruta Andina gasta CLP 4,2 millones mensuales en búsqueda y redes. El ROAS reportado es 6,1 pero incluye clientes que ya eran clientes.",
        "riesgo": "Atribuirse demanda existente, inflar el retorno y decidir presupuesto sobre una ilusión.",
    },
    {
        "num": "15",
        "slug": "part-15-e-commerce-y-marketplaces",
        "titulo": "E-commerce y marketplaces",
        "nivel": "Adquisición",
        "resultado": "operar una tienda y un canal de marketplace con economía verificable",
        "pregunta": "¿Dónde se pierde el pedido y cuánto queda después de comisión, envío y devolución?",
        "artefacto": "simulación de tienda rentable con catálogo, checkout, costos y plan postventa",
        "competencias": ["conversión en comercio digital", "economía por pedido", "cumplimiento al consumidor"],
        "roles": ["E-commerce manager", "Marketplace specialist", "Emprendedor"],
        "libros": ["krug", "eisenberg", "laja", "flint", "chaffey", "fader"],
        "caso": "La línea de hardware de Ruta Andina vende bien en marketplace y pierde dinero: comisión de 16 %, despachos subsidiados y 9 % de devoluciones.",
        "riesgo": "Incumplir derecho de retracto, garantía legal y reglas de información al consumidor.",
    },
    {
        "num": "16",
        "slug": "part-16-crm-pipeline-y-sales-operations",
        "titulo": "CRM, pipeline y sales operations",
        "nivel": "Operación de ingresos",
        "resultado": "convertir el CRM en un sistema de trabajo y de verdad operacional",
        "pregunta": "¿El pipeline describe la realidad o solo el optimismo del equipo?",
        "artefacto": "diseño de sales operations con pipeline, criterios de etapa, forecast y gobierno de datos",
        "competencias": ["diseño de pipeline", "forecast disciplinado", "higiene y gobierno de datos"],
        "roles": ["Sales operations", "RevOps analyst", "Jefe de ventas"],
        "libros": ["roberge", "diorio", "grove", "miller-heiman", "zoltners", "wheeler-dv"],
        "caso": "El CRM de Ruta Andina tiene 380 oportunidades abiertas, 44 % sin actividad en 30 días y tres definiciones distintas de «propuesta enviada».",
        "riesgo": "Tomar decisiones de contratación y presupuesto sobre un pipeline que no representa la realidad.",
    },
    {
        "num": "17",
        "slug": "part-17-marketing-automation-y-revenue-operations",
        "titulo": "Marketing automation y revenue operations",
        "nivel": "Operación de ingresos",
        "resultado": "integrar marketing, ventas y servicio en un solo modelo de datos y de proceso",
        "pregunta": "¿Qué automatizo porque mejora el sistema y qué estaría solo escalando un desorden?",
        "artefacto": "operating model de RevOps con lifecycle, scoring, SLA, integraciones y observabilidad",
        "competencias": ["automatización con propósito", "modelo de datos de ingresos", "gobernanza operativa"],
        "roles": ["Marketing ops", "RevOps manager", "Sales ops"],
        "libros": ["diorio", "roberge", "grove", "kaplan-norton", "provost", "nist-airmf"],
        "caso": "Marketing entrega 300 leads mensuales y ventas trabaja 60. Cada área tiene su propio informe y ambos son correctos según su definición.",
        "riesgo": "Automatizar comunicaciones sin base de licitud ni control de calidad y multiplicar el daño.",
    },
    {
        "num": "18",
        "slug": "part-18-customer-experience-success-y-fidelizacion",
        "titulo": "Customer experience, success y fidelización",
        "nivel": "Operación de ingresos",
        "resultado": "sostener y expandir el ingreso existente con un sistema de valor entregado",
        "pregunta": "¿En qué momento el cliente obtiene valor y qué lo hace quedarse o irse?",
        "artefacto": "sistema de retención y expansión con onboarding, health score, renovación y advocacy",
        "competencias": ["diseño de onboarding", "gestión de salud de cuenta", "análisis de cohortes"],
        "roles": ["Customer success manager", "Account manager", "Head of CS"],
        "libros": ["mehta", "dixon-effort", "reichheld", "fader", "hulick", "fader-ltv"],
        "caso": "Ruta Andina pierde 3,4 % de cuentas al mes. El 61 % de las bajas nunca completó la carga inicial de datos y jamás usó el módulo de pagos.",
        "riesgo": "Retener con castigos contractuales en lugar de valor entregado y dañar reputación.",
    },
    {
        "num": "19",
        "slug": "part-19-growth-marketing-y-growth-engineering",
        "titulo": "Growth marketing y growth engineering",
        "nivel": "Crecimiento y analítica",
        "resultado": "instalar un motor de experimentación que produzca aprendizaje acumulativo",
        "pregunta": "¿Qué bucle hace que el crecimiento se retroalimente en lugar de depender del gasto?",
        "artefacto": "growth model con North Star, bucles, backlog priorizado y resultados de experimentos",
        "competencias": ["diseño de bucles de crecimiento", "priorización de experimentos", "activación y retención"],
        "roles": ["Growth manager", "Growth engineer", "Head of Growth"],
        "libros": ["ellis-brown", "bush-plg", "croll-yoskovitz", "kohavi", "ries-lean", "cagan"],
        "caso": "Ruta Andina hace 12 «experimentos» al mes y no puede nombrar un solo aprendizaje que haya cambiado el producto o el canal.",
        "riesgo": "Declarar victorias con muestras insuficientes y optimizar métricas locales que dañan el sistema.",
    },
    {
        "num": "20",
        "slug": "part-20-analitica-comercial-y-marketing-science",
        "titulo": "Analítica comercial y marketing science",
        "nivel": "Crecimiento y analítica",
        "resultado": "sostener decisiones de ingreso con métricas correctamente construidas",
        "pregunta": "¿Esta cifra mide lo que creo que mide, y qué decisión cambiaría si estuviera equivocada?",
        "artefacto": "caso analítico integral con árbol de métricas, cohortes, incrementalidad y dashboard ejecutivo",
        "competencias": ["construcción de métricas", "análisis de cohortes", "diseño de experimentos y atribución"],
        "roles": ["Marketing analyst", "Revenue analyst", "Data-driven marketer"],
        "libros": ["kaushik", "croll-yoskovitz", "kohavi", "provost", "wheeler-dv", "hubbard"],
        "caso": "El CAC reportado por Ruta Andina excluye sueldos comerciales y el LTV usa un margen bruto que nunca fue validado con contabilidad.",
        "riesgo": "Escalar inversión sobre una economía unitaria que no resiste una revisión financiera.",
    },
    {
        "num": "21",
        "slug": "part-21-ia-aplicada-a-marketing-ventas-y-servicio",
        "titulo": "IA aplicada a marketing, ventas y servicio",
        "nivel": "IA y expansión",
        "resultado": "usar IA como capacidad operativa con evaluación, control y responsabilidad humana",
        "pregunta": "¿Qué tarea mejora con IA, cómo sé que mejora y quién responde cuando falla?",
        "artefacto": "operating model humano-IA con casos de uso, evaluaciones, guardrails y registro de incidentes",
        "competencias": ["diseño de casos de uso de IA", "evaluación de salidas", "gobernanza y privacidad"],
        "roles": ["Growth manager con IA", "RevOps", "Marketing manager", "Sales enablement"],
        "libros": ["russell-norvig", "ng-mlyearning", "nist-airmf", "oneil", "provost", "kohavi"],
        "caso": "Ruta Andina automatizó respuestas de soporte con un modelo generativo. En dos semanas prometió por escrito una funcionalidad que no existe.",
        "riesgo": "Publicar contenido incorrecto a escala, tratar datos personales sin base legal y perder trazabilidad.",
    },
    {
        "num": "22",
        "slug": "part-22-go-to-market-canales-y-expansion",
        "titulo": "Go-to-market, canales y expansión",
        "nivel": "IA y expansión",
        "resultado": "diseñar el modo en que la oferta llega al mercado y decide crecer",
        "pregunta": "¿Qué movimiento comercial corresponde al valor del contrato, al ciclo y al comprador?",
        "artefacto": "plan GTM completo con beachhead, movimiento comercial, canales, economía y plan de lanzamiento",
        "competencias": ["selección de movimiento GTM", "economía de canales", "planificación de lanzamiento"],
        "roles": ["Head of GTM", "Partnerships", "Product marketing", "Founder"],
        "libros": ["moore", "weinberg-traction", "bush-plg", "ross", "porter-hbr", "rumelt"],
        "caso": "Ruta Andina quiere entrar a Perú y, al mismo tiempo, lanzar un plan self-service y un programa de partners contables. El equipo es el mismo.",
        "riesgo": "Abrir frentes simultáneos sin capacidad, diluir foco y llegar tarde a todos.",
    },
    {
        "num": "23",
        "slug": "part-23-direccion-comercial-cmo-vp-sales-y-cro",
        "titulo": "Dirección comercial: CMO, VP Sales y CRO",
        "nivel": "Dirección y Capstone",
        "resultado": "dirigir la función de ingresos: personas, sistema, números y gobierno",
        "pregunta": "¿Qué debe existir para que el resultado no dependa de que yo esté en cada reunión?",
        "artefacto": "operating system del CRO con estructura, plan, cadencia, incentivos y reporte al directorio",
        "competencias": ["diseño organizacional comercial", "gestión por indicadores", "gobierno y cultura"],
        "roles": ["CMO", "VP Sales", "CRO", "Gerente comercial"],
        "libros": ["grove", "doerr", "zoltners", "collins", "lencioni", "kaplan-norton"],
        "caso": "El directorio pide duplicar ingresos en 18 meses. La propuesta inicial del equipo es contratar seis vendedores más sin cambiar proceso ni oferta.",
        "riesgo": "Escalar un motor roto, generar rotación y destruir el margen mientras se «crece».",
    },
    {
        "num": "24",
        "slug": "part-24-empresa-real-regulacion-y-capstone",
        "titulo": "Empresa real, regulación y Capstone",
        "nivel": "Dirección y Capstone",
        "resultado": "integrar todo el programa en una operación comercial defendible y conforme a la normativa chilena",
        "pregunta": "¿Esta operación resiste una revisión comercial, financiera, legal y ética al mismo tiempo?",
        "artefacto": "Capstone completo: empresa, evidencia, números, cumplimiento y defensa ejecutiva",
        "competencias": ["integración estratégica", "cumplimiento normativo aplicado", "comunicación ejecutiva"],
        "roles": ["Founder", "CRO", "Consultor senior", "Gerente general"],
        "libros": ["rumelt", "osterwalder-bmg", "iso-31000", "diorio", "ellet", "kaplan-norton"],
        "caso": "El Capstone exige presentar la operación completa de Ruta Andina —o de una empresa propia— ante un panel que revisará números, evidencia y cumplimiento.",
        "riesgo": "Presentar un plan atractivo que no cumple la Ley 19.496, la Ley 21.719 o las reglas de libre competencia.",
    },
]

NIVELES = [
    ("Fundamentos", "01–04", "Mercado, cliente, investigación y posicionamiento"),
    ("Oferta comercial", "05–07", "Producto, marca y monetización"),
    ("Venta", "08–11", "Proceso comercial, B2B, negociación y prospección"),
    ("Adquisición", "12–15", "Digital, contenido, medios pagados y comercio electrónico"),
    ("Operación de ingresos", "16–18", "CRM, RevOps y Customer Success"),
    ("Crecimiento y analítica", "19–20", "Growth y marketing science"),
    ("IA y expansión", "21–22", "IA comercial y go-to-market"),
    ("Dirección y Capstone", "23–24", "Operating system del CRO y empresa integrada"),
]


def por_numero(num):
    for parte in PARTES:
        if parte["num"] == num:
            return parte
    raise KeyError("Parte inexistente: {}".format(num))
